/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * bank.java
 *
 * Created on Dec 10, 2014, 1:38:25 PM
 */

package Master;

//For shadow
import Master.Model.BankMod;
import Master.Service.MasterData;
import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.util.Iterator;
import java.util.LinkedList;
import java.util.List;
import javax.swing.border.LineBorder;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user1
 */
public class Bank extends javax.swing.JPanel {

    //attrib for shadow starts************************************************
    protected int strokeSize = 1;
    protected Color shadowColor = Color.black;
    protected boolean shady = true;
    protected boolean highQuality = true;
    protected Dimension arcs = new Dimension(20, 20);
    protected int shadowGap = 5;
    protected int shadowOffset = 4;
    protected int shadowAlpha = 150;
//attrib for shadow stops***********************************************
    String t1,t2,t3;
    MasterData mdt =null;
    /** Creates new form bank */
    public Bank() {
         setOpaque(false);
        initComponents();
        generateCodeViews();
        btndel.setEnabled(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TabPane = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        Bt1 = new javax.swing.JTextField();
        Bt2 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        btnsave = new javax.swing.JButton();
        btnnew = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        btndel = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnclose = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        banktab = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(650, 400));

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        TabPane.setFont(new java.awt.Font("Baskerville Old Face", 1, 14));
        TabPane.setPreferredSize(new java.awt.Dimension(770, 421));

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel16.setText("Bank Name:");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel6.setText("Bank Branch:");

        Bt1.setFont(new java.awt.Font("Times New Roman", 1, 14));
        Bt1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        Bt1.setPreferredSize(new java.awt.Dimension(6, 23));
        Bt1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Bt1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Bt1KeyTyped(evt);
            }
        });

        Bt2.setFont(new java.awt.Font("Times New Roman", 1, 14));
        Bt2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        Bt2.setPreferredSize(new java.awt.Dimension(6, 23));
        Bt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt2ActionPerformed(evt);
            }
        });
        Bt2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Bt2KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel24))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Bt2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Bt1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Bt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(192, 192, 192)
                .addComponent(jLabel24)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnsave.setFont(new java.awt.Font("Lucida Fax", 1, 14));
        btnsave.setText("SAVE");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });
        btnsave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnsaveKeyPressed(evt);
            }
        });

        btnnew.setFont(new java.awt.Font("Lucida Fax", 1, 14));
        btnnew.setText("NEW");
        btnnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnewActionPerformed(evt);
            }
        });
        btnnew.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnnewKeyPressed(evt);
            }
        });

        btnclear.setFont(new java.awt.Font("Lucida Fax", 1, 14));
        btnclear.setText("CLEAR");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });
        btnclear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnclearKeyPressed(evt);
            }
        });

        btndel.setFont(new java.awt.Font("Lucida Fax", 1, 14));
        btndel.setText("DELETE");
        btndel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndelActionPerformed(evt);
            }
        });
        btndel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btndelKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnnew)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnsave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btndel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnclear)
                .addGap(185, 185, 185))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnnew)
                    .addComponent(btnsave)
                    .addComponent(btnclear)
                    .addComponent(btndel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        TabPane.addTab("Entry", jPanel2);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Bank");

        btnclose.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnclose.setText("CLOSE");
        btnclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncloseActionPerformed(evt);
            }
        });
        btnclose.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btncloseKeyPressed(evt);
            }
        });

        banktab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Bank Name", "Bank Branch"
            }
        ));
        banktab.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                banktabKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(banktab);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(TabPane, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addComponent(jLabel4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnclose)
                        .addGap(28, 28, 28)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(9, 9, 9)
                        .addComponent(TabPane, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnclose))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btncloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncloseActionPerformed
        // TODO add your handling code here:
        Admin.Forms.MainMenu.PanelInfo.removeAll();
        Admin.Forms.MainMenu.PanelInfo.repaint();
}//GEN-LAST:event_btncloseActionPerformed

    private void Bt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt2ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_Bt2ActionPerformed

    private void Bt1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Bt1KeyPressed
        // TODO add your handling code here:
        int keycode=evt.getKeyCode();
      if(keycode==10)
      {
          Bt2.requestFocus(true);

      }
        if(evt.getKeyCode()==java.awt.event.KeyEvent.VK_DOWN)
    {
	Bt2.requestFocus();
    }
       
      
    }//GEN-LAST:event_Bt1KeyPressed

    private void Bt2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Bt2KeyPressed
        // TODO add your handling code here:
        int keycode=evt.getKeyCode();
      if(keycode==10)
      {
          btnsave.requestFocus();

      }
        if(evt.getKeyCode()==java.awt.event.KeyEvent.VK_UP)
    {
	Bt1.requestFocus();
    }
    }//GEN-LAST:event_Bt2KeyPressed

    private void btnnewKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnnewKeyPressed
        // TODO add your handling code here:

    if(evt.getKeyCode()==java.awt.event.KeyEvent.VK_RIGHT)
    {
	btnsave.requestFocus();
    }
    if(evt.getKeyCode()==java.awt.event.KeyEvent.VK_DOWN)
    {
	btnclose.requestFocus();
    }
    }//GEN-LAST:event_btnnewKeyPressed

    private void btnsaveKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnsaveKeyPressed
        // TODO add your handling code here:
        int keycode=evt.getKeyCode();
        if(keycode==10)
      {
          btnsave.doClick();

      }
    }//GEN-LAST:event_btnsaveKeyPressed

    private void btnclearKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnclearKeyPressed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_btnclearKeyPressed

    private void btncloseKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btncloseKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode()==java.awt.event.KeyEvent.VK_UP)
        {
	btnnew.requestFocus();

        }
    }//GEN-LAST:event_btncloseKeyPressed

    private void btnnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnewActionPerformed
        // TODO add your handling code here:
        clear();
        btnnew.setEnabled(false);
        btnsave.setEnabled(true);

    }//GEN-LAST:event_btnnewActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling code here:
        t1=Bt1.getText().trim();
        t2=Bt2.getText().trim();
        boolean vf=ValidateFeilds();
        if(vf)
        {

                mdt=new MasterData();
                boolean flag=false;
                flag=mdt.saveBank(t1, t2);
                if(flag)
                {
                    JOptionPane.showMessageDialog(null, "Bank Saved Successfully");
                    btnnew.setEnabled(true);
                    btnsave.setEnabled(false);
                    generateCodeViews();
                }
                else
                {
                    JOptionPane.showMessageDialog(null,"Bank Not Saved Successfully");
                }

        }
    }//GEN-LAST:event_btnsaveActionPerformed
    public void generateCodeViews()
    {
        System.out.println("Viw 1");
        int i=0,j=0;
        mdt=new MasterData();
        BankMod bnk=null;
        List lst=new LinkedList();
        lst=(List)mdt.getBankTab();
        Object dat[][]=new Object[lst.size()][3];
        String col[]={"Bank","Branch"};
        Iterator itm=lst.iterator();
        while(itm.hasNext())
        {
            bnk=(BankMod)itm.next();
            dat[i][0]=(String)bnk.getBankName();
            dat[i][1]=(String)bnk.getBankBranch();
            i++;
        }
       DefaultTableModel dm=new DefaultTableModel(dat,col);
       banktab.setModel(dm);
       banktab.setAutoResizeMode(banktab.AUTO_RESIZE_OFF);
       banktab.getColumnModel().getColumn(0).setPreferredWidth(100);
       banktab.getColumnModel().getColumn(1).setPreferredWidth(160);
    }
    private void Bt1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Bt1KeyTyped
        // TODO add your handling code here:
       
    }//GEN-LAST:event_Bt1KeyTyped

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        // TODO add your handling code here:
        Bt1.setText("");
        Bt2.setText("");
        Bt1.requestFocus();
    }//GEN-LAST:event_btnclearActionPerformed

    private void btndelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndelActionPerformed
        // TODO add your handling code here:
        t1=Bt1.getText().trim();
       // bs=new BankServices();
        boolean flag=false;
       // flag=bs.DELBank(t1);
        if(flag)
        {
            JOptionPane.showMessageDialog(null, "Bank Deleted");
            btnnew.setEnabled(true);
            btndel.setEnabled(false);
            generateCodeViews();
        }
        else
        {JOptionPane.showMessageDialog(null,"Bank Not deleted");}
    }//GEN-LAST:event_btndelActionPerformed

    private void btndelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btndelKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btndelKeyPressed

    private void banktabKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_banktabKeyPressed
        // TODO add your handling code here:
        int keycode=evt.getKeyCode();
            if(keycode==10)
            {
            try
            {
            int ro=banktab.getSelectedRow();
            String bk=banktab.getModel().getValueAt(ro,0).toString();
            mdt =new MasterData();
            BankMod bnk=(BankMod)mdt.viewbycode(bk);
            Bt1.setText(bnk.getBankName());
            Bt2.setText(bnk.getBankBranch());
            btndel.setEnabled(true);
            btnsave.setEnabled(false);
            }
            catch(Exception e){JOptionPane.showMessageDialog(this,"Dont Select on the blank Row");}
            }

    }//GEN-LAST:event_banktabKeyPressed
    private boolean ValidateFeilds() {
    if(t1.length()==0){JOptionPane.showMessageDialog(null,"Enter Bank Name");return false;}
    if(t2.length()==0){JOptionPane.showMessageDialog(null,"Enter Branch Name");return false;}
    return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Bt1;
    private javax.swing.JTextField Bt2;
    private javax.swing.JTabbedPane TabPane;
    private javax.swing.JTable banktab;
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btnclose;
    private javax.swing.JButton btndel;
    private javax.swing.JButton btnnew;
    private javax.swing.JButton btnsave;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    //fun for creating shadow Starts**************************************************************
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        int width = getWidth();
        int height = getHeight();
        int shadowGap = this.shadowGap;
        Color shadowColorA = new Color(shadowColor.getRed(),
	shadowColor.getGreen(), shadowColor.getBlue(), shadowAlpha);
        Graphics2D graphics = (Graphics2D) g;

        //Sets antialiasing if HQ.
        if (highQuality) {
            graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING,
			RenderingHints.VALUE_ANTIALIAS_ON);
        }

        //Draws shadow borders if any.
        if (shady) {
            graphics.setColor(shadowColorA);
            graphics.fillRoundRect(
                    shadowOffset,// X position
                    shadowOffset,// Y position
                    width - strokeSize - shadowOffset, // width
                    height - strokeSize - shadowOffset, // height
                    arcs.width, arcs.height);// arc Dimension
        } else {
            shadowGap = 1;
        }

        //Draws the rounded opaque panel with borders.
        graphics.setColor(getBackground());
        graphics.fillRoundRect(0, 0, width - shadowGap, height - shadowGap, arcs.width, arcs.height);
        graphics.setColor(getForeground());
        graphics.setStroke(new BasicStroke(strokeSize));
        graphics.drawRoundRect(0, 0, width - shadowGap,
		height - shadowGap, arcs.width, arcs.height);

        //Sets strokes to default, is better.
        graphics.setStroke(new BasicStroke());
    }
    //fun for creating shadow Stops**************************************************************


    public void clear()
    {
        Bt1.setText("");
         Bt2.setText("");
         Bt1.requestFocus();
    }
}
