/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CashWise.java
 *
 * Created on Mar 27, 2015, 11:24:08 AM
 */

package Forms;

import APMCMain.GETOC;
import Forms.Models.CstModel;
import Forms.Models.PayModel;
import Forms.Models.TrnPayModel;
import Forms.Services.CustomerSrvs;
import Forms.Services.PrdWiseSrvs;
import Forms.Services.TranSrvs;
import java.awt.Font;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Iterator;
import java.util.LinkedList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import org.joda.time.DateTime;
import org.joda.time.Days;

/**
 *
 * @author user
 */
public class CashWise extends javax.swing.JInternalFrame {
    String gdat;
    String tid;
    String cid;
    String t1,t2,t3,t5;
    Double tt3,tt4,tt6,tt7,tt8,tt9,tt10;
    TableRowSorter<TableModel> rowsort;
    /** Creates new form CashWise */
    public CashWise() {
        super("Cash Payment",false,true,false,true);
        initComponents();
        getTableDATA();
        MyFont.setUIFont (new javax.swing.plaf.FontUIResource ("Tunga",Font.BOLD,16));
        pdat.setDate(new java.util.Date());
        //-------------------------Seacrh Table String From Text Field------------------------------------------
        rowsort=new TableRowSorter<TableModel>(csttab.getModel());
        csttab.setRowSorter(rowsort);
        cntxt.getDocument().addDocumentListener(new DocumentListener()
        {
            @Override
            public void insertUpdate(DocumentEvent e)
            {
                String text = cntxt.getText();
                if (text.trim().length() == 0)
                {rowsort.setRowFilter(null);}
                else
                {rowsort.setRowFilter(RowFilter.regexFilter("(?i)" + text));}
            }
            @Override
            public void removeUpdate(DocumentEvent e)
            {
                String text = cntxt.getText();
                if (text.trim().length() == 0)
                {rowsort.setRowFilter(null);}
                else
                {rowsort.setRowFilter(RowFilter.regexFilter("(?i)" + text));}
            }
            @Override
            public void changedUpdate(DocumentEvent e)
            {throw new UnsupportedOperationException("Not supported yet.");} //To change body of generated methods, choose Tools | Templates.
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        l2 = new javax.swing.JLabel();
        l9 = new javax.swing.JLabel();
        l8 = new javax.swing.JLabel();
        l7 = new javax.swing.JLabel();
        pt4 = new javax.swing.JLabel();
        pt5 = new javax.swing.JLabel();
        l10 = new javax.swing.JLabel();
        l11 = new javax.swing.JLabel();
        pt6 = new javax.swing.JComboBox();
        pt7 = new javax.swing.JLabel();
        l12 = new javax.swing.JLabel();
        l13 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        pt1 = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();
        l15 = new javax.swing.JLabel();
        pt8 = new javax.swing.JLabel();
        l14 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        pdat = new com.toedter.calendar.JDateChooser();
        pclr = new javax.swing.JButton();
        pupdt = new javax.swing.JButton();
        psave = new javax.swing.JButton();
        pt3 = new javax.swing.JTextField();
        l16 = new javax.swing.JLabel();
        pt2 = new javax.swing.JTextField();
        pidcmb = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        trntab = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        csttab = new javax.swing.JTable();
        cntxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/sanlogo.png"))); // NOI18N
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 0, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel10.setOpaque(false);
        jPanel10.setLayout(null);

        l2.setFont(new java.awt.Font("Tunga", 1, 18));
        l2.setForeground(new java.awt.Color(255, 236, 24));
        l2.setText("ಪಾವತಿ ವಿವರ");
        jPanel10.add(l2);
        l2.setBounds(130, 10, 88, 23);

        l9.setFont(new java.awt.Font("Lucida Fax", 1, 14));
        l9.setForeground(new java.awt.Color(51, 255, 0));
        l9.setText("Rs/-");
        jPanel10.add(l9);
        l9.setBounds(290, 310, 31, 30);

        l8.setFont(new java.awt.Font("Tunga", 1, 16));
        l8.setForeground(new java.awt.Color(51, 255, 51));
        l8.setText("   ವ್ಯವಹಾರಿಕ ಸಾಲದ ಮೊತ್ತ :");
        jPanel10.add(l8);
        l8.setBounds(10, 160, 170, 29);

        l7.setFont(new java.awt.Font("Tunga", 1, 16));
        l7.setForeground(new java.awt.Color(51, 255, 51));
        l7.setText(" ಹಣ :");
        jPanel10.add(l7);
        l7.setBounds(140, 310, 40, 30);

        pt4.setBackground(new java.awt.Color(0, 255, 0));
        pt4.setFont(new java.awt.Font("Lucida Bright", 1, 14));
        pt4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pt4.setOpaque(true);
        jPanel10.add(pt4);
        pt4.setBounds(180, 120, 50, 30);

        pt5.setBackground(new java.awt.Color(0, 255, 0));
        pt5.setFont(new java.awt.Font("Lucida Bright", 1, 14));
        pt5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pt5.setOpaque(true);
        jPanel10.add(pt5);
        pt5.setBounds(180, 160, 100, 30);

        l10.setFont(new java.awt.Font("Lucida Fax", 1, 14));
        l10.setForeground(new java.awt.Color(51, 255, 0));
        l10.setText("Rs/-");
        jPanel10.add(l10);
        l10.setBounds(290, 160, 40, 30);

        l11.setFont(new java.awt.Font("Tunga", 1, 16));
        l11.setForeground(new java.awt.Color(51, 255, 51));
        l11.setText("  ಬಡ್ಡಿ ಶೆಕಡ :");
        jPanel10.add(l11);
        l11.setBounds(100, 200, 80, 24);

        pt6.setFont(new java.awt.Font("Times New Roman", 1, 14));
        pt6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Select-", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        pt6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pt6ActionPerformed(evt);
            }
        });
        pt6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pt6KeyPressed(evt);
            }
        });
        jPanel10.add(pt6);
        pt6.setBounds(180, 200, 90, 20);

        pt7.setBackground(new java.awt.Color(0, 255, 0));
        pt7.setFont(new java.awt.Font("Lucida Bright", 1, 14));
        pt7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pt7.setOpaque(true);
        jPanel10.add(pt7);
        pt7.setBounds(180, 230, 90, 30);

        l12.setFont(new java.awt.Font("Tunga", 1, 16));
        l12.setForeground(new java.awt.Color(51, 255, 51));
        l12.setText("  ಕೊಟ್ಟ ಹಣಕ್ಕೆ ಬಡ್ಡಿಸೆರಿಸಿ :");
        jPanel10.add(l12);
        l12.setBounds(30, 230, 150, 29);

        l13.setFont(new java.awt.Font("Lucida Fax", 1, 14));
        l13.setForeground(new java.awt.Color(51, 255, 0));
        l13.setText("Rs/-");
        jPanel10.add(l13);
        l13.setBounds(280, 230, 31, 30);

        l4.setFont(new java.awt.Font("Tunga", 1, 16));
        l4.setForeground(new java.awt.Color(51, 255, 51));
        l4.setText(" ಪಾವತಿದಾರನ ಹೆಸರು :");
        jPanel10.add(l4);
        l4.setBounds(40, 270, 140, 30);

        pt1.setBackground(new java.awt.Color(0, 255, 0));
        pt1.setFont(new java.awt.Font("Lucida Bright", 1, 14));
        pt1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pt1.setOpaque(true);
        jPanel10.add(pt1);
        pt1.setBounds(180, 40, 38, 30);

        l1.setFont(new java.awt.Font("Lucida Fax", 1, 14));
        l1.setForeground(new java.awt.Color(51, 255, 0));
        l1.setText(" PayID :");
        jPanel10.add(l1);
        l1.setBounds(120, 40, 60, 30);

        l15.setFont(new java.awt.Font("Lucida Fax", 1, 14));
        l15.setForeground(new java.awt.Color(51, 255, 0));
        l15.setText("Rs/-");
        jPanel10.add(l15);
        l15.setBounds(280, 350, 31, 30);

        pt8.setBackground(new java.awt.Color(0, 255, 0));
        pt8.setFont(new java.awt.Font("Lucida Bright", 1, 14));
        pt8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pt8.setOpaque(true);
        jPanel10.add(pt8);
        pt8.setBounds(180, 350, 92, 30);

        l14.setFont(new java.awt.Font("Tunga", 1, 16));
        l14.setForeground(new java.awt.Color(51, 255, 51));
        l14.setText("ಬಾಕಿ ಮೊತ್ತ :");
        jPanel10.add(l14);
        l14.setBounds(100, 350, 80, 29);

        l3.setFont(new java.awt.Font("Tunga", 1, 16));
        l3.setForeground(new java.awt.Color(51, 255, 51));
        l3.setText("  ದಿನಾಂಕ :");
        jPanel10.add(l3);
        l3.setBounds(110, 80, 70, 30);
        jPanel10.add(pdat);
        pdat.setBounds(180, 80, 130, 30);

        pclr.setFont(new java.awt.Font("Lucida Fax", 1, 11));
        pclr.setText("CLEAR");
        pclr.setOpaque(false);
        pclr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pclrActionPerformed(evt);
            }
        });
        jPanel10.add(pclr);
        pclr.setBounds(270, 400, 71, 23);

        pupdt.setFont(new java.awt.Font("Lucida Fax", 1, 11));
        pupdt.setText("UPDATE");
        pupdt.setOpaque(false);
        pupdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pupdtActionPerformed(evt);
            }
        });
        jPanel10.add(pupdt);
        pupdt.setBounds(140, 400, 79, 23);

        psave.setFont(new java.awt.Font("Lucida Fax", 1, 11));
        psave.setText("SAVE");
        psave.setOpaque(false);
        psave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                psaveActionPerformed(evt);
            }
        });
        psave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                psaveKeyPressed(evt);
            }
        });
        jPanel10.add(psave);
        psave.setBounds(20, 400, 74, 23);

        pt3.setFont(new java.awt.Font("Georgia", 1, 14));
        pt3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        pt3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pt3KeyPressed(evt);
            }
        });
        jPanel10.add(pt3);
        pt3.setBounds(180, 310, 100, 30);

        l16.setFont(new java.awt.Font("Tunga", 1, 16));
        l16.setForeground(new java.awt.Color(51, 255, 51));
        l16.setText("   ವ್ಯವಹಾರಿಕ ಸಂಖ್ಯೆ :");
        jPanel10.add(l16);
        l16.setBounds(50, 120, 130, 30);

        pt2.setFont(new java.awt.Font("Tunga", 1, 16));
        pt2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        pt2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pt2KeyPressed(evt);
            }
        });
        jPanel10.add(pt2);
        pt2.setBounds(180, 270, 130, 30);

        pidcmb.setFont(new java.awt.Font("Times New Roman", 1, 14));
        pidcmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pidcmbActionPerformed(evt);
            }
        });
        jPanel10.add(pidcmb);
        pidcmb.setBounds(250, 40, 80, 30);

        trntab.setBackground(new java.awt.Color(0, 0, 0));
        trntab.setFont(new java.awt.Font("Tunga", 1, 18));
        trntab.setForeground(new java.awt.Color(51, 255, 0));
        trntab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        trntab.setGridColor(new java.awt.Color(51, 255, 0));
        trntab.setSelectionBackground(new java.awt.Color(51, 255, 0));
        trntab.setSelectionForeground(new java.awt.Color(0, 0, 0));
        trntab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                trntabMouseClicked(evt);
            }
        });
        trntab.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                trntabKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(trntab);

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setOpaque(false);

        csttab.setBackground(new java.awt.Color(0, 0, 0));
        csttab.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        csttab.setFont(new java.awt.Font("Arial Unicode MS", 1, 16));
        csttab.setForeground(new java.awt.Color(0, 255, 0));
        csttab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "", ""
            }
        ));
        csttab.setGridColor(new java.awt.Color(51, 255, 0));
        csttab.setOpaque(false);
        csttab.setRowHeight(20);
        csttab.setSelectionBackground(new java.awt.Color(51, 255, 0));
        csttab.setSelectionForeground(new java.awt.Color(0, 0, 0));
        csttab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                csttabMouseClicked(evt);
            }
        });
        csttab.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                csttabKeyPressed(evt);
            }
        });
        jScrollPane3.setViewportView(csttab);

        cntxt.setBackground(new java.awt.Color(51, 255, 0));
        cntxt.setFont(new java.awt.Font("Arial Unicode MS", 1, 18));
        cntxt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        cntxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cntxtKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Fax", 1, 14));
        jLabel1.setForeground(new java.awt.Color(51, 255, 51));
        jLabel1.setText("Type Text Here To Search :-");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(cntxt, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(11, 11, 11)
                .addComponent(cntxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pt6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pt6ActionPerformed
        // TODO add your handling code here:
        try {
            //old date----------------------------------
            DateFormat formatter = null;
            Date cDate = null;
            
            Calendar old = Calendar.getInstance();
            formatter = new SimpleDateFormat("yyyy-MM-dd");
            cDate = (Date) formatter.parse(gdat);
           // java.util.Date dat=new java.util.Date(cd.getTime());
            old.setTime(new java.util.Date(cDate.getTime()));
            int oyy=old.get(Calendar.YEAR);
            int omm=old.get(Calendar.MONTH);
            int odd=old.get(Calendar.DATE);
            //-------------------------------------------
            //present date---------------------------------
            Calendar now = Calendar.getInstance();
            now.setTime(new java.util.Date(pdat.getDate().getTime()));
            int nyy=now.get(Calendar.YEAR);
            int nmm=now.get(Calendar.MONTH);
            int ndd=now.get(Calendar.DATE);
            //----------------------------------------------
            Date past = new Date(oyy, omm, odd); // June 20th, 2010
            Date today = new Date(nyy, nmm, ndd); // July 24th
            int days = Days.daysBetween(new DateTime(past), new DateTime(today)).getDays();
            // int month = Months.monthsBetween(new DateTime(past), new DateTime(today)).getMonths();
            // int mnth = month+1;
            int td=days+1;
            if(td<30) {
                int tday=30;
                int cm1=tday/30;
                Double ga=Double.valueOf(pt5.getText());
                Double itrs=Double.valueOf(pt6.getSelectedItem().toString());
                Double cga=ga/100;
                Double ci=cga*itrs;
                Double cti=ci*cm1;
                double tamt=ga+cti;
                pt7.setText(String.valueOf(tamt));
            }
            if(td>30) {
                int mnt2=td/30;
                Double ga=Double.valueOf(pt5.getText());
                Double itrs=Double.valueOf(pt6.getSelectedItem().toString());
                Double cga=ga/100;
                Double ci=cga*itrs;
                Double cti=ci*mnt2;
                double tamt=ga+cti;
                pt7.setText(String.valueOf(tamt));
                
            }
        } catch(Exception e){JOptionPane.showMessageDialog(this, "Error is ="+e);}
}//GEN-LAST:event_pt6ActionPerformed

    private void psaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_psaveActionPerformed
        // TODO add your handling code here:
        
        t1=pt1.getText();
        t2=pt2.getText();
        t3=pt3.getText();
        tt4=Double.valueOf(pt4.getText());
        t5=pt5.getText();
        tt6=Double.valueOf(pt6.getSelectedItem().toString());
        tt7=Double.valueOf(pt7.getText());
        tt8=Double.valueOf(pt8.getText());
        tt9=0.0;
        tt10=0.0;
        boolean vp=validpaym();
        if(vp)
        {
            boolean flag=false;
            PrdWiseSrvs pwsrv=new PrdWiseSrvs();
            java.sql.Date pdt=new java.sql.Date(pdat.getDate().getTime());
            flag=pwsrv.savePrdPay(cid, t1, pdt, "-", "-", tt4, t5, tt6, tt7, tt8, tt9, tt10, t3, tt3);
            if(flag)
            {
                updateTrn();
            }else{updatetrnPay("Opened");JOptionPane.showMessageDialog(this, "ಕ್ಷಮಿಸಿ ಹಣವನ್ನು ಪಾವತಿಸಲು ಸಾದ್ಯವಾಗುತ್ತಿಲ್ಲ");}
        }
    }//GEN-LAST:event_psaveActionPerformed
    public void updateTrn()
    {
        boolean flag=false;
        tid=pt5.getText();
        String sts="Closed";
        TranSrvs tsrv=new TranSrvs();
        flag=tsrv.UpdateSTS(cid,tid,sts);
        if(flag)
        {updatetrnPay("Closed");}else{JOptionPane.showMessageDialog(this, "Transaction Update Failed");}
    }
    public void updatetrnPay(String sts)
    {
        boolean flag=false;
        tid=pt5.getText();
        TranSrvs tsrv=new TranSrvs();
        Double ba=Double.valueOf(pt8.getText());
        Double pa=Double.valueOf(pt7.getText());
        flag=tsrv.UpdateTPSTS(cid,tid,sts,ba,pa);
        if(flag)
        {JOptionPane.showMessageDialog(this, "ಹಣವನ್ನು ಪಾವತಿಸಲಾಗಿದೆ");}else{JOptionPane.showMessageDialog(this, "Transaction Payemnt Update Failed");}}
    private boolean validpaym()
    {
        if(pdat.getDate()==null){JOptionPane.showMessageDialog(this, "ದಯವಿಟ್ಟು ದಿನಾಂಕವನ್ನು ಹೊಂದಿಸಿ");return false;}
        if(t2.length()==0){JOptionPane.showMessageDialog(this, "ದಯವಿಟ್ಟು ಪಾವತಿದಾರನ ಹೆಸರುನಮೊದಿಸಿ");return false;}
        if(t3.length()==0){JOptionPane.showMessageDialog(this, "ದಯವಿಟ್ಟು ಪಾವತಿ ಹಣವನ್ನು ನಮೊದಿಸಿ");return false;}
        try{tt3=Double.valueOf(t3);}catch(Exception e){JOptionPane.showMessageDialog(this, "ದಯವಿಟ್ಟು ಪಾವತಿ ಹಣವನ್ನು ಸಂಖ್ಯೆಗಳಲ್ಲಿ ನಮೊದಿಸಿ");return false;}
        if(pt6.getSelectedIndex()==0){JOptionPane.showMessageDialog(this, "ದಯವಿಟ್ಟು ವಿತರಿಸಿದ ಒಟ್ಟು ಮೊತ್ತಕ್ಕೆ ಬಡ್ಡಿಯನ್ನು ಆಯ್ದುಕೊಳ್ಳಿ");return false;}
        return true;
    }
    private void trntabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_trntabMouseClicked
        // TODO add your handling code here:
        clr();
        int ro=trntab.getSelectedRow();
        tid=trntab.getModel().getValueAt(ro,0).toString();
        gdat=trntab.getModel().getValueAt(ro,1).toString();
        String amt=trntab.getModel().getValueAt(ro,2).toString();
        pt4.setText(tid);
        pt5.setText(amt);
        nxtPID(tid);
        comboPIDs(cid,tid);
}//GEN-LAST:event_trntabMouseClicked

    private void trntabKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_trntabKeyPressed
        // TODO add your handling code here:
        int keycode=evt.getKeyCode();
        if(keycode==10) {
            clr();
            int ro=trntab.getSelectedRow();
            tid=trntab.getModel().getValueAt(ro,0).toString();
            gdat= trntab.getModel().getValueAt(ro,1).toString();
            String amt=trntab.getModel().getValueAt(ro,2).toString();
            pt4.setText(tid);
            pt5.setText(amt);
            nxtPID(tid);
            comboPIDs(cid,tid);
        }
}//GEN-LAST:event_trntabKeyPressed

    private void csttabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_csttabMouseClicked
        // TODO add your handling code here:
        try {
            int ro=csttab.getSelectedRow();
            cid=csttab.getModel().getValueAt(ro,0).toString();
            getTRNTable(cid);

        }catch(Exception e){}
}//GEN-LAST:event_csttabMouseClicked

    private void csttabKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_csttabKeyPressed
        // TODO add your handling code here:
        int keycode=evt.getKeyCode();
        if(keycode==10) {
            int ro=csttab.getSelectedRow();
            cid=csttab.getModel().getValueAt(ro,0).toString();
            getTRNTable(cid);
        }
}//GEN-LAST:event_csttabKeyPressed

    private void cntxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cntxtKeyPressed
        // TODO add your handling code here:
        int key=evt.getKeyCode();
        if(key==10) {
            csttab.requestFocus();
        }
}//GEN-LAST:event_cntxtKeyPressed

    private void pt2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pt2KeyPressed
        // TODO add your handling code here:
       if(evt.getKeyCode()==0)
       {
           pt3.requestFocus();
       }
    }//GEN-LAST:event_pt2KeyPressed

    private void pupdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pupdtActionPerformed
        // TODO add your handling code here:
        t1=pt1.getText();
        t2=pt2.getText();
        t3=pt3.getText();
        tt4=Double.valueOf(pt4.getText());
        t5=pt5.getText();
        tt6=Double.valueOf(pt6.getSelectedItem().toString());
        tt7=Double.valueOf(pt7.getText());
        tt8=Double.valueOf(pt8.getText());
        tt9=0.0;
        tt10=0.0;
        boolean vp=validpaym();
        if(vp)
        {
            boolean flag=false;
            PrdWiseSrvs pwsrv=new PrdWiseSrvs();
            java.sql.Date pdt=new java.sql.Date(pdat.getDate().getTime());
            flag=pwsrv.UpdatePrdPay(cid, t1,"-", "-", tt4, t5, tt6, tt7, tt8, tt9, tt10, t3, tt3);
            if(flag)
            {
                updateTrn();
            }else{updatetrnPay("Opened");JOptionPane.showMessageDialog(this, "ಕ್ಷಮಿಸಿ ಹಣವನ್ನು ಪಾವತಿಸಲು ಸಾದ್ಯವಾಗುತ್ತಿಲ್ಲ");}
        }
    }//GEN-LAST:event_pupdtActionPerformed

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        // TODO add your handling code here:
        GETOC.pc=0;
    }//GEN-LAST:event_formInternalFrameClosed

    private void pclrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pclrActionPerformed
        // TODO add your handling code here:
        clr();
    }//GEN-LAST:event_pclrActionPerformed
    public void clr()
    {
        pt2.setText("");
        pt3.setText("");
        pt4.setText("");
        pt5.setText("");
        pt6.setSelectedIndex(0);
        pt7.setText("");
        pt8.setText("");
    }
    private void pidcmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pidcmbActionPerformed
        // TODO add your handling code here:
        if(pidcmb.getSelectedIndex()!=0)
        {
            String pid=(String) pidcmb.getSelectedItem();
            PrdWiseSrvs pwsrv=new PrdWiseSrvs();
            PayModel paym=null;
            paym=(PayModel)pwsrv.getPayData(cid, tid, pid);
            String chk=paym.getPname();
            if(!chk.equals(""))
            {
                pt1.setText(paym.getPid());
                java.util.Date d=new java.util.Date();
                d=paym.getPaydate();
                pdat.setDate(d);
                pt2.setText(paym.getPname());
                pt3.setText(String.valueOf(paym.getBcamt()));
                pt4.setText(paym.getTid());
                pt5.setText(String.valueOf(paym.getTrnamt()));
                pt6.setSelectedItem(paym.getIntrest());
                pt7.setText(String.valueOf(paym.getWtintrst()));
                pt8.setText(String.valueOf(paym.getDueamt()));
                pupdt.setEnabled(true);
            }else{JOptionPane.showMessageDialog(this, "ಈ ID ಯು ಹಣದ ಪಾವತಿಗೆ ಅನ್ವಯಿಸುವುದಿಲ್ಲ");}
        }
    }//GEN-LAST:event_pidcmbActionPerformed

    private void pt6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pt6KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10)
        {
            try {
            //old date----------------------------------
            DateFormat formatter = null;
            Date cDate = null;

            Calendar old = Calendar.getInstance();
            formatter = new SimpleDateFormat("yyyy-MM-dd");
            cDate = (Date) formatter.parse(gdat);
           // java.util.Date dat=new java.util.Date(cd.getTime());
            old.setTime(new java.util.Date(cDate.getTime()));
            int oyy=old.get(Calendar.YEAR);
            int omm=old.get(Calendar.MONTH);
            int odd=old.get(Calendar.DATE);
            //-------------------------------------------
            //present date---------------------------------
            Calendar now = Calendar.getInstance();
            now.setTime(new java.util.Date(pdat.getDate().getTime()));
            int nyy=now.get(Calendar.YEAR);
            int nmm=now.get(Calendar.MONTH);
            int ndd=now.get(Calendar.DATE);
            //----------------------------------------------
            Date past = new Date(oyy, omm, odd); // June 20th, 2010
            Date today = new Date(nyy, nmm, ndd); // July 24th
            int days = Days.daysBetween(new DateTime(past), new DateTime(today)).getDays();
            // int month = Months.monthsBetween(new DateTime(past), new DateTime(today)).getMonths();
            // int mnth = month+1;
            int td=days+1;
            if(td<30) {
                int tday=30;
                int cm1=tday/30;
                Double ga=Double.valueOf(pt5.getText());
                Double itrs=Double.valueOf(pt6.getSelectedItem().toString());
                Double cga=ga/100;
                Double ci=cga*itrs;
                Double cti=ci*cm1;
                double tamt=ga+cti;
                pt7.setText(String.valueOf(tamt));
            }
            if(td>30) {
                int mnt2=td/30;
                Double ga=Double.valueOf(pt5.getText());
                Double itrs=Double.valueOf(pt6.getSelectedItem().toString());
                Double cga=ga/100;
                Double ci=cga*itrs;
                Double cti=ci*mnt2;
                double tamt=ga+cti;
                pt7.setText(String.valueOf(tamt));
            }
            pt2.requestFocus();
        } catch(Exception e){JOptionPane.showMessageDialog(this, "Error is ="+e);}
        }
    }//GEN-LAST:event_pt6KeyPressed

    private void pt3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pt3KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==0)
        {
            try
            {
                Double wi =Double.valueOf(pt7.getText());
                Double pa=Double.valueOf(pt3.getText());
                Double cb=wi-pa;
                pt8.setText(String.valueOf(cb));
                psave.requestFocus();
            }catch(Exception e){}
        }
    }//GEN-LAST:event_pt3KeyPressed

    private void psaveKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_psaveKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10)
        {
            psave.doClick();
        }
    }//GEN-LAST:event_psaveKeyPressed
    public void comboPIDs(String cid,String tid)
    {
        try
        {
            int i=0;
            List lst=null;
            PrdWiseSrvs prdws = new PrdWiseSrvs();
            lst=(List)prdws.getPIDcmb(cid,tid);
            String cods[]=new String[lst.size()];
            Iterator itm1=lst.iterator();
            while(itm1.hasNext())
            {
                cods[i]=(String)itm1.next();
                i++;
            }
            pidcmb.setModel(new javax.swing.DefaultComboBoxModel(cods));
            pidcmb.setMaximumRowCount(6);
            pidcmb.setFocusable(true);
        }catch(Exception e){JOptionPane.showMessageDialog(this,"Initialization Failed Please Try Again"+e);}
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cntxt;
    private javax.swing.JTable csttab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l10;
    private javax.swing.JLabel l11;
    private javax.swing.JLabel l12;
    private javax.swing.JLabel l13;
    private javax.swing.JLabel l14;
    private javax.swing.JLabel l15;
    private javax.swing.JLabel l16;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l7;
    private javax.swing.JLabel l8;
    private javax.swing.JLabel l9;
    private javax.swing.JButton pclr;
    private com.toedter.calendar.JDateChooser pdat;
    private javax.swing.JComboBox pidcmb;
    private javax.swing.JButton psave;
    private javax.swing.JLabel pt1;
    private javax.swing.JTextField pt2;
    private javax.swing.JTextField pt3;
    private javax.swing.JLabel pt4;
    private javax.swing.JLabel pt5;
    private javax.swing.JComboBox pt6;
    private javax.swing.JLabel pt7;
    private javax.swing.JLabel pt8;
    private javax.swing.JButton pupdt;
    private javax.swing.JTable trntab;
    // End of variables declaration//GEN-END:variables
    Object tabdata[][];
    public void getTableDATA()
    {
        tabdata=null;
        int i=0,j=0;
        CustomerSrvs csr=new CustomerSrvs();
        CstModel cstm=null;
        List lst=new LinkedList();
        lst=(List)csr.getcstTab();
        tabdata=new Object[lst.size()][13];
        String col[]={"ಖಾತೆ ನಂ","ಹೆಸರು"};
        Iterator itm=lst.iterator();
        while(itm.hasNext())
        {
            cstm=(CstModel)itm.next();
            tabdata[i][0]=(String)cstm.getCid();
            tabdata[i][1]=(String)cstm.getCnam();
            i++;
        }
       DefaultTableModel dm =new DefaultTableModel(tabdata,col);
       csttab.setModel(dm);
       csttab.setAutoResizeMode(csttab.AUTO_RESIZE_OFF);
       csttab.getColumnModel().getColumn(0).setPreferredWidth(70);
       csttab.getColumnModel().getColumn(1).setPreferredWidth(130);
    }
    public void getTRNTable(String cid)
    {
        int i=0,j=0;
        TranSrvs tsrv =new TranSrvs();
        TrnPayModel tpm=null;
        List lst=new LinkedList();
        lst=(List)tsrv.getTTPrd(cid);
        Object[][] tadata=new Object[lst.size()][5];
        String col[]={"Trn ID","ದಿನಾಂಕ","ಹಣ ಮೊತ್ತ"};
        Iterator itm=lst.iterator();
        while(itm.hasNext())
        {
            tpm=(TrnPayModel)itm.next();
            tadata[i][0]=(String)tpm.getTid();
            tadata[i][1]=(Date)tpm.getTdate();
            tadata[i][2]=(Double)tpm.getTotamt();
            i++;
        }
       DefaultTableModel dm =new DefaultTableModel(tadata,col);
       trntab.setModel(dm);
       trntab.setAutoResizeMode(trntab.AUTO_RESIZE_OFF);
       trntab.getColumnModel().getColumn(0).setPreferredWidth(100);
       trntab.getColumnModel().getColumn(1).setPreferredWidth(180);
       trntab.getColumnModel().getColumn(1).setPreferredWidth(180);
    }
    public void nxtPID(String tid)
    {
        PrdWiseSrvs pwsr=new PrdWiseSrvs();
        List ls=null;
        ls= pwsr.NxtPslno(cid,tid);
        int cod=ls.size();
        int nex=cod+1;
        pt1.setText(String.valueOf(nex));
    }
}
