/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CustomerREG.java
 *
 * Created on Mar 3, 2015, 1:59:58 PM
 */

package Forms;

import APMCMain.GETOC;
import APMCMain.MainFrm;
import Forms.Models.CstModel;
import Forms.Services.CustomerSrvs;
import java.awt.Color;
import java.awt.Font;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.Calendar;
import java.util.Date;
import java.util.Iterator;
import java.util.LinkedList;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class CustReg extends javax.swing.JInternalFrame {
    String t1,t2,t3,t4,t5,img1;
    java.sql.Date dt=null;
    /** Creates new form CustomerREG */
    public CustReg() throws IOException {
        super("Customer Entry",false,true,false,true);
        MainFrm mf=new MainFrm();
      //  this.setBorder(null);
        initComponents();
        MyFont.setUIFont (new javax.swing.plaf.FontUIResource ("Tunga",Font.BOLD,16));
        this.setBorder(BorderFactory.createLineBorder(Color.WHITE));this.updateUI();
        setBounds(10,10,600,500);
        updatebtn.setEnabled(false);
        savebtn.setEnabled(false);
        dat.setDate(new java.util.Date());
        autoupload();
        getTableDATA();
        getNamecmb();
        getIDcmb();
    }
    public void autoupload() throws IOException
    {
        File fp=new File("src\\Icons\\personal.png");
       // ImageIcon ipr= new ImageIcon(fp.getPath());
        BufferedImage myPic = ImageIO.read(fp.getAbsoluteFile());
        cstpic.setIcon(new ImageIcon(myPic.getScaledInstance(170, 201, 100)));
        img1=fp.getAbsolutePath();
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt3 = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        txt2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt5 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        cstpic = new javax.swing.JLabel();
        capturebtn = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        txt4 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        savebtn = new javax.swing.JButton();
        addbtn = new javax.swing.JButton();
        updatebtn = new javax.swing.JButton();
        clrbtn = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        cnocmb = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        namcmb = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        dat = new com.toedter.calendar.JDateChooser();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        csttab = new javax.swing.JTable();

        setBackground(new java.awt.Color(59, 0, 59));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setDoubleBuffered(true);
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/sanlogo.png"))); // NOI18N
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 0, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel6.setFont(new java.awt.Font("Arial Unicode MS", 1, 18));
        jLabel6.setForeground(new java.awt.Color(51, 255, 0));
        jLabel6.setText("ಖಾತೆ ವಿವರಣೆ");

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel4.setOpaque(false);

        txt3.setColumns(15);
        txt3.setFont(new java.awt.Font("Arial Unicode MS", 1, 18));
        txt3.setRows(3);
        txt3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jScrollPane2.setViewportView(txt3);

        jLabel8.setFont(new java.awt.Font("Arial Unicode MS", 1, 18));
        jLabel8.setForeground(new java.awt.Color(51, 255, 0));
        jLabel8.setText("ಮೊಬೈಲ್‍ ಸಂಖ್ಯೆ");

        txt2.setFont(new java.awt.Font("Arial Unicode MS", 1, 18));
        txt2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel9.setFont(new java.awt.Font("Arial Unicode MS", 1, 18));
        jLabel9.setForeground(new java.awt.Color(51, 255, 0));
        jLabel9.setText("ವಿಳಾಸ");

        jLabel10.setFont(new java.awt.Font("Arial Unicode MS", 1, 18));
        jLabel10.setForeground(new java.awt.Color(51, 255, 0));
        jLabel10.setText("ಖಾತೆದಾರನ ಹೆಸರು");

        txt1.setBackground(new java.awt.Color(51, 255, 51));
        txt1.setFont(new java.awt.Font("Lucida Bright", 1, 14));
        txt1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt1.setOpaque(true);

        jLabel12.setFont(new java.awt.Font("Arial Unicode MS", 1, 18));
        jLabel12.setForeground(new java.awt.Color(51, 255, 0));
        jLabel12.setText("ಖಾತೆ ಸಂಖ್ಯೆ");

        txt5.setFont(new java.awt.Font("Tunga", 1, 16));
        txt5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jPanel5.setBackground(new java.awt.Color(92, 34, 92));

        cstpic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/personal.png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cstpic, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cstpic, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
        );

        capturebtn.setFont(new java.awt.Font("Arial Unicode MS", 1, 18));
        capturebtn.setForeground(new java.awt.Color(0, 102, 0));
        capturebtn.setText("ಪೊಟೊ");
        capturebtn.setOpaque(false);

        jLabel15.setFont(new java.awt.Font("Arial Unicode MS", 1, 18));
        jLabel15.setForeground(new java.awt.Color(51, 255, 0));
        jLabel15.setText("ಊರು");

        txt4.setFont(new java.awt.Font("Arial Unicode MS", 1, 18));
        txt4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel8))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt4, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt5, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(capturebtn)
                        .addGap(79, 79, 79))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(152, 152, 152)
                                .addComponent(jLabel15))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(6, 6, 6)
                                    .addComponent(txt4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txt5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel8))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(capturebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel6.setOpaque(false);

        savebtn.setFont(new java.awt.Font("Euphemia", 1, 14));
        savebtn.setForeground(new java.awt.Color(7, 74, 7));
        savebtn.setText("SAVE");
        savebtn.setOpaque(false);
        savebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebtnActionPerformed(evt);
            }
        });

        addbtn.setFont(new java.awt.Font("Euphemia", 1, 14));
        addbtn.setForeground(new java.awt.Color(7, 74, 7));
        addbtn.setText("ADD NEW");
        addbtn.setOpaque(false);
        addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });

        updatebtn.setFont(new java.awt.Font("Euphemia", 1, 14));
        updatebtn.setForeground(new java.awt.Color(7, 74, 7));
        updatebtn.setText("UPDATE");
        updatebtn.setOpaque(false);
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });

        clrbtn.setFont(new java.awt.Font("Euphemia", 1, 14));
        clrbtn.setForeground(new java.awt.Color(7, 74, 7));
        clrbtn.setText("CLEAR");
        clrbtn.setOpaque(false);
        clrbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clrbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(savebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(updatebtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clrbtn)
                .addContainerGap(172, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(savebtn, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(updatebtn, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(clrbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel7.setOpaque(false);

        cnocmb.setFont(new java.awt.Font("Lucida Bright", 1, 14));
        cnocmb.setForeground(new java.awt.Color(0, 102, 0));
        cnocmb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Select-" }));
        cnocmb.setOpaque(false);
        cnocmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnocmbActionPerformed(evt);
            }
        });
        cnocmb.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cnocmbKeyPressed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Arial Unicode MS", 1, 18));
        jLabel13.setForeground(new java.awt.Color(51, 255, 0));
        jLabel13.setText("ಖಾತೆ ಸಂಖ್ಯೆ");

        namcmb.setFont(new java.awt.Font("Arial Unicode MS", 1, 18));
        namcmb.setForeground(new java.awt.Color(0, 102, 0));
        namcmb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Select-" }));
        namcmb.setOpaque(false);
        namcmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namcmbActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Arial Unicode MS", 1, 18));
        jLabel14.setForeground(new java.awt.Color(51, 255, 0));
        jLabel14.setText("ಖಾತೆದಾರನ ಹೆಸರು");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cnocmb, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(namcmb, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namcmb, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cnocmb, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel11.setFont(new java.awt.Font("Arial Unicode MS", 1, 18));
        jLabel11.setForeground(new java.awt.Color(51, 255, 0));
        jLabel11.setText("ದಿನಾಂಕ");

        dat.setBackground(new java.awt.Color(0, 0, 0));
        dat.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        dat.setDateFormatString("dd/MM/yyyy");
        dat.setFont(new java.awt.Font("Lucida Bright", 1, 14));
        dat.setOpaque(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 229, Short.MAX_VALUE)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dat, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, 0, 568, Short.MAX_VALUE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(51, 0, 51));
        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        csttab.setBackground(new java.awt.Color(0, 0, 0));
        csttab.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        csttab.setFont(new java.awt.Font("Arial Unicode MS", 1, 18));
        csttab.setForeground(new java.awt.Color(0, 255, 0));
        csttab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        csttab.setGridColor(new java.awt.Color(51, 255, 0));
        csttab.setOpaque(false);
        csttab.setRowHeight(20);
        csttab.setSelectionBackground(new java.awt.Color(51, 255, 0));
        csttab.setSelectionForeground(new java.awt.Color(0, 0, 0));
        csttab.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                csttabKeyPressed(evt);
            }
        });
        jScrollPane3.setViewportView(csttab);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        // TODO add your handling code here:
        GETOC.c1=0;
    }//GEN-LAST:event_formInternalFrameClosed

    private void cnocmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnocmbActionPerformed
        // TODO add your handling code here:
        String id=(String) cnocmb.getSelectedItem();
        if(!id.equals("-Select-"))
        {
        try{
            t1=(String) cnocmb.getSelectedItem();
            addtofield(t1);
        }catch(Exception e){}
        }
    }//GEN-LAST:event_cnocmbActionPerformed

    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtnActionPerformed
        // TODO add your handling code here:
        getNextCid();
        clrall();
        savebtn.setEnabled(true);
    }//GEN-LAST:event_addbtnActionPerformed
    public void getNextCid()
    {
        CustomerSrvs csr=new CustomerSrvs();
        List ls=null;
        ls= csr.getNextCId();
        int cod=ls.size();
        Calendar old = Calendar.getInstance();
        old.setTime(new java.util.Date());
        int yy=old.get(Calendar.YEAR);
        int nex=(yy*1000)+cod+1;
        txt1.setText(String.valueOf(nex));
    }
    public void clrall()
    {
        txt2.setText("");
        txt3.setText("");
        txt4.setText("");
        txt5.setText("");
    }
    private void namcmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namcmbActionPerformed
        // TODO add your handling code here:
        try
        {

            CustomerSrvs csr=new CustomerSrvs();
            CstModel cstm=null;
            t2=(String) namcmb.getSelectedItem();
            cstm=(CstModel)csr.getcstBname(t2);
            cnocmb.setSelectedItem(cstm.getCid());
            namcmb.setSelectedItem(cstm.getCnam());
            txt1.setText(cstm.getCid());
            txt2.setText(cstm.getCnam());
            txt3.setText(cstm.getCaddrs());
            txt4.setText(cstm.getCtown());
            txt5.setText(cstm.getCphno());
            String ppath=cstm.getCpic();
            File fl=new File(ppath);
            BufferedImage myPic = ImageIO.read(fl.getAbsoluteFile());
            cstpic.setIcon(new ImageIcon(myPic.getScaledInstance(170, 201, 100)));
            img1=fl.getAbsolutePath();
            savebtn.setEnabled(false);
            updatebtn.setEnabled(true);
        }catch(Exception e){JOptionPane.showMessageDialog(this,"ಹುಡುಕಲು ಸಾದ್ಯವಾಗುತಿಲ್ಲ ಪುನಃ ಪ್ರಯತ್ನಿಸಿ"+e);}
            updatebtn.setEnabled(true);
            savebtn.setEnabled(false);
    }//GEN-LAST:event_namcmbActionPerformed

    private void savebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtnActionPerformed
        // TODO add your handling code here:
        t1=txt1.getText();
        t2=txt2.getText();
        t3=txt3.getText();
        t4=txt4.getText();
        t5=txt5.getText();
        boolean vf=validcinf();
        if(vf)
        {
            dt=new java.sql.Date(dat.getDate().getTime());
            boolean flag=false;
            CustomerSrvs csr=new CustomerSrvs();
            flag=csr.savecst(t1,dt, t2, t3, t4, t5, img1);
            if(flag)
            {
                addcst();
            }else{JOptionPane.showMessageDialog(this, "ಕ್ಷ್ಮಮಿಸಿ ಖಾತೆದಾರನ ವಿವರಗಳನ್ನು ಉಳಿಸಲು ಸಾದ್ಯವಾಗುತಿಲ್ಲ");}
        } 
    }//GEN-LAST:event_savebtnActionPerformed
    public void addcst()
    {
        boolean flag=false;
        CustomerSrvs csr=new CustomerSrvs();
        String ic=t2+t1;
        flag=csr.saveSubcst(t1,ic);
        if(flag)
        {
            getTableDATA();
            JOptionPane.showMessageDialog(this, "ಖಾತೆದಾರನ ವಿವರಗಳನ್ನು ಉಳಿಸಲಗಿದೆ.");
            getTableDATA();
            getNamecmb();
            getIDcmb();
        }else{JOptionPane.showMessageDialog(this, "ಕ್ಷ್ಮಮಿಸಿ ಖಾತೆದಾರನ ವಿವರಗಳನ್ನು ಉಳಿಸಲು ಸಾದ್ಯವಾಗುತಿಲ್ಲ");}

    }
    private void clrbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clrbtnActionPerformed
        // TODO add your handling code here:
        clrall();
    }//GEN-LAST:event_clrbtnActionPerformed

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
        // TODO add your handling code here:
        t1=txt1.getText();
        t2=txt2.getText();
        t3=txt3.getText();
        t4=txt4.getText();
        t5=txt5.getText();
        boolean vf=validcinf();
        if(vf)
        {
            boolean flag=false;
            CustomerSrvs csr=new CustomerSrvs();
            flag=csr.Updatecst(t1,t2, t3, t4, t5, img1);
            if(flag)
            {
                Updatecst();
            }else{JOptionPane.showMessageDialog(this, "ಖಾತೆದಾರನ ವಿವರಗಳು Update ಮಾಡಲು ಸಾದ್ಯವಾಗುತಿಲ್ಲ");}
        } 
    }//GEN-LAST:event_updatebtnActionPerformed
    public void Updatecst()
    {
        boolean flag=false;
        CustomerSrvs csr=new CustomerSrvs();
        String ic=t2+t1;
        flag=csr.UpdtSubcst(t1,ic);
        if(flag)
        {
            JOptionPane.showMessageDialog(this, "ಖಾತೆದಾರನ ವಿವರಗಳು Update ಆಗಿದೆ");
            getTableDATA();
            getNamecmb();
            getIDcmb();
        }else{JOptionPane.showMessageDialog(this, "ಖಾತೆದಾರನ ವಿವರಗಳು Update ಮಾಡಲು ಸಾದ್ಯವಾಗುತಿಲ್ಲ");}
       
    }
    private void csttabKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_csttabKeyPressed
        // TODO add your handling code here:
        int keycode=evt.getKeyCode();
            if(keycode==10)
            {
                try{
                int ro=csttab.getSelectedRow();
                t1=csttab.getModel().getValueAt(ro,0).toString();
                addtofield(t1);
                }catch(Exception e){}
            }
        if(keycode==java.awt.event.KeyEvent.VK_UP)
        {
             try{
            int ro=csttab.getSelectedRow();
            t1=csttab.getModel().getValueAt(ro-1,0).toString();
            addtofield(t1);
             }catch(Exception e){}
        }
        if(keycode==java.awt.event.KeyEvent.VK_DOWN)
        {   try{
            int ro=csttab.getSelectedRow();
            t1=csttab.getModel().getValueAt(ro+1,0).toString();
            addtofield(t1);
            }catch(Exception e){}
        }
        //||(keycode==java.awt.event.KeyEvent.VK_DOWN)
    }//GEN-LAST:event_csttabKeyPressed

    private void cnocmbKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cnocmbKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cnocmbKeyPressed
    public void addtofield(String cid)
    {
        try
        {
            CustomerSrvs csr=new CustomerSrvs();
            CstModel cstm=null;
            cstm=(CstModel)csr.getcstBid(cid);
            namcmb.setSelectedItem(cstm.getCnam());
            cnocmb.setSelectedItem(cid);
            txt1.setText(cstm.getCid());
            txt2.setText(cstm.getCnam());
            txt3.setText(cstm.getCaddrs());
            txt4.setText(cstm.getCtown());
            txt5.setText(cstm.getCphno());
            String ppath=cstm.getCpic();
            File fl=new File(ppath);
            BufferedImage myPic = ImageIO.read(fl.getAbsoluteFile());
            cstpic.setIcon(new ImageIcon(myPic.getScaledInstance(170, 201, 100)));
            img1=fl.getAbsolutePath();
            savebtn.setEnabled(false);
            updatebtn.setEnabled(true);
        }catch(Exception e){JOptionPane.showMessageDialog(this,"ಹುಡುಕಲು ಸಾದ್ಯವಾಗುತಿಲ್ಲ ಪುನಃ ಪ್ರಯತ್ನಿಸಿ");}
    }
    private boolean validcinf()
    {
        if(t2.length()==0){JOptionPane.showMessageDialog(this, "ದಯವಿಟ್ಟು ಖಾತೆದಾರನ ಹೆಸರನ್ನು ನಮೊದಿಸಿ");return false;}
        if(t3.length()==0){JOptionPane.showMessageDialog(this, "ದಯವಿಟ್ಟು ಖಾತೆದಾರನ ವಿಳಾಸವನ್ನು ನಮೊದಿಸಿ");return false;}
        if(t4.length()==0){JOptionPane.showMessageDialog(this, "ದಯವಿಟ್ಟು ಖಾತೆದಾರನ ಊರನ್ನು ನಮೊದಿಸಿ");return false;}
        if(!t5.matches("\\d{10}")){JOptionPane.showMessageDialog(this, "ದಯವಿಟ್ಟು ಸರಿಯಾದ ಮೊಬೈಲ್‍ ಸಂಖ್ಯೆಯನ್ನು ನಮೊದಿಸಿ");return false;}
        if(dat.getDate()==null){JOptionPane.showMessageDialog(this, "ದಯವಿಟ್ಟು ದಿನಾಂಕವನ್ನು ಸರಿಹೊಂದಿಸಿ");return false;}
        File fl=new File("src\\Froms\\personal.png");
        String img=fl.getAbsolutePath();
        if(img.equals(img1))
        {
            int dialogButton = JOptionPane.YES_NO_OPTION;
            JOptionPane.showConfirmDialog (null, "ಖಾತೆದಾರನ ಫೊಟೊ ಸ್ವಿಕರಿಸಲಿಲ್ಲ\nಮುಂದುವರೆಯಲು (Yes) ಅಥವಾ ಕ್ಲಿಕ್ಕಿಸಲು (No) ಆಯ್ದುಕೊಳ್ಳಿ ","Warning",dialogButton);
            if(dialogButton!=JOptionPane.YES_OPTION){capturebtn.requestFocus();return false;}
        }
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbtn;
    private javax.swing.JButton capturebtn;
    private javax.swing.JButton clrbtn;
    private javax.swing.JComboBox cnocmb;
    private javax.swing.JLabel cstpic;
    private javax.swing.JTable csttab;
    private com.toedter.calendar.JDateChooser dat;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JComboBox namcmb;
    private javax.swing.JButton savebtn;
    private javax.swing.JLabel txt1;
    private javax.swing.JTextField txt2;
    private javax.swing.JTextArea txt3;
    private javax.swing.JTextField txt4;
    private javax.swing.JTextField txt5;
    private javax.swing.JButton updatebtn;
    // End of variables declaration//GEN-END:variables

    //_____________________All Methods And Function ____________________________________________________
    public void getTableDATA()
    {
        int i=0,j=0;
        CustomerSrvs csr=new CustomerSrvs();
        CstModel cstm=null;
        List lst=new LinkedList();
        lst=(List)csr.getcstTab();
        Object dat[][]=new Object[lst.size()][13];
        String col[]={"ಖಾತೆ ಸಂಖ್ಯೆ","ಹೆಸರು","ಊರು","ಮೊಬೈಲ್‍ ಸಂಖ್ಯೆ"};
        Iterator itm=lst.iterator();
        while(itm.hasNext())
        {
            cstm=(CstModel)itm.next();
            dat[i][0]=(String)cstm.getCid();
            dat[i][1]=(String)cstm.getCnam();
            dat[i][2]=(String)cstm.getCtown();
            dat[i][3]=(String)cstm.getCphno();
            i++;
        }
       DefaultTableModel dm=new DefaultTableModel(dat,col);
       csttab.setModel(dm);
       csttab.setAutoResizeMode(csttab.AUTO_RESIZE_OFF);
       csttab.getColumnModel().getColumn(0).setPreferredWidth(90);
       csttab.getColumnModel().getColumn(1).setPreferredWidth(130);
       csttab.getColumnModel().getColumn(2).setPreferredWidth(150);
       csttab.getColumnModel().getColumn(3).setPreferredWidth(100);
    }
    public void getIDcmb()
    {
        int i=0;
        List lst=null;
        CustomerSrvs csr=new CustomerSrvs();
        lst=csr.getCIDcmb();
        String per[]=new String[lst.size()];
        Iterator itm1=lst.iterator();
        while(itm1.hasNext())
        {
            per[i]=(String)itm1.next();
            i++;
        }
        cnocmb.setModel(new javax.swing.DefaultComboBoxModel(per));
        cnocmb.setMaximumRowCount(6);
        cnocmb.setFocusable(true);
   }
    public void getNamecmb()//getIDcmb()
    {
        int i=0;
        List lst=null;
        CustomerSrvs csr=new CustomerSrvs();
        lst=csr.getCnamcmb();
        String per[]=new String[lst.size()];
        Iterator itm1=lst.iterator();
        while(itm1.hasNext())
        {
            per[i]=(String)itm1.next();
            i++;
        }
        namcmb.setModel(new javax.swing.DefaultComboBoxModel(per));
        namcmb.setMaximumRowCount(6);
        namcmb.setFocusable(true);
   }
    //____________________________Methods ANd Function Ends__________________________________________________________
}
