/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FinalRepGen.java
 *
 * Created on Apr 2, 2015, 11:16:14 AM
 */

package Forms;

import APMCMain.GETOC;
import APMCMain.MainFrm;
import Forms.Models.CstModel;
import Forms.Models.CstPrdSellModel;
import Forms.Models.PrdActModel;
import Forms.Models.PrdInvModel;
import Forms.Reports.FinalPrd;
import Forms.Reports.FinalTRN;
import Forms.Services.CustomerSrvs;
import Forms.Services.PrdWiseSrvs;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.*;
import java.awt.*;
import java.io.File;
import java.util.HashMap;
import java.util.List;
import java.util.Iterator;
import java.util.LinkedList;
import javax.swing.*;
import javax.swing.RowFilter;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
/**
 *
 * @author user
 */
public class FinalRepGen extends javax.swing.JInternalFrame {
    TableRowSorter<TableModel> rowsort;
    String cid;
    String cnam;
    /** Creates new form FinalRepGen */
    public FinalRepGen() {
        super("Reports",false,true,false,true);
        initComponents();
        getTableDATA();
        MyFont.setUIFont (new javax.swing.plaf.FontUIResource ("Arial Unicode MS",Font.BOLD,16));
        this.setBorder(BorderFactory.createLineBorder(Color.WHITE));this.updateUI();
        repbtn.setEnabled(false);

        //-------------------------Seacrh Table String From Text Field------------------------------------------
        rowsort=new TableRowSorter<TableModel>(csttab.getModel());
        csttab.setRowSorter(rowsort);
        cntxt.getDocument().addDocumentListener(new DocumentListener()
        {
            @Override
            public void insertUpdate(DocumentEvent e)
            {
                String text = cntxt.getText();
                if (text.trim().length() == 0)
                {rowsort.setRowFilter(null);}
                else
                {rowsort.setRowFilter(RowFilter.regexFilter("(?i)" + text));}
            }
            @Override
            public void removeUpdate(DocumentEvent e)
            {
                String text = cntxt.getText();
                if (text.trim().length() == 0)
                {rowsort.setRowFilter(null);}
                else
                {rowsort.setRowFilter(RowFilter.regexFilter("(?i)" + text));}
            }
            @Override
            public void changedUpdate(DocumentEvent e)
            {throw new UnsupportedOperationException("Not supported yet.");} //To change body of generated methods, choose Tools | Templates.
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        csttab = new javax.swing.JTable();
        cntxt = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txt1 = new javax.swing.JLabel();
        codcmb = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt4 = new javax.swing.JLabel();
        txt5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        repbtn = new javax.swing.JButton();
        cidlbl = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        report = new javax.swing.JDesktopPane();

        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/sanlogo.png"))); // NOI18N
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel1.setBackground(new java.awt.Color(68, 7, 68));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Lucida Fax", 1, 14));
        jLabel1.setForeground(new java.awt.Color(51, 255, 51));
        jLabel1.setText("Type Text Here To Search :-");

        csttab.setBackground(new java.awt.Color(0, 0, 0));
        csttab.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        csttab.setFont(new java.awt.Font("Arial Unicode MS", 1, 18));
        csttab.setForeground(new java.awt.Color(0, 255, 0));
        csttab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "", ""
            }
        ));
        csttab.setGridColor(new java.awt.Color(51, 255, 0));
        csttab.setOpaque(false);
        csttab.setRowHeight(20);
        csttab.setSelectionBackground(new java.awt.Color(51, 255, 0));
        csttab.setSelectionForeground(new java.awt.Color(0, 0, 0));
        csttab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                csttabMouseClicked(evt);
            }
        });
        csttab.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                csttabKeyPressed(evt);
            }
        });
        jScrollPane3.setViewportView(csttab);

        cntxt.setBackground(new java.awt.Color(51, 255, 0));
        cntxt.setFont(new java.awt.Font("Arial Unicode MS", 1, 18));
        cntxt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        cntxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cntxtKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cntxt, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(11, 11, 11)
                .addComponent(cntxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setOpaque(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setOpaque(false);
        jPanel2.setLayout(null);

        txt1.setBackground(new java.awt.Color(51, 255, 0));
        txt1.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        txt1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt1.setOpaque(true);
        jPanel2.add(txt1);
        txt1.setBounds(170, 80, 140, 30);

        codcmb.setFont(new java.awt.Font("Arial Unicode MS", 0, 18)); // NOI18N
        codcmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codcmbActionPerformed(evt);
            }
        });
        jPanel2.add(codcmb);
        codcmb.setBounds(170, 40, 120, 31);

        jLabel2.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 255, 51));
        jLabel2.setText("ಉತ್ಪನ್ನದ Codes :");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(10, 40, 147, 25);

        jLabel4.setFont(new java.awt.Font("Akshar Unicode", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 255, 51));
        jLabel4.setText("   ಉತ್ಪನ್ನ :");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(90, 80, 70, 30);

        txt2.setBackground(new java.awt.Color(51, 255, 0));
        txt2.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        txt2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt2.setOpaque(true);
        jPanel2.add(txt2);
        txt2.setBounds(170, 120, 120, 30);

        jLabel7.setFont(new java.awt.Font("Arial Unicode MS", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 255, 51));
        jLabel7.setText("ಹರಾಜು ಕ್ರಂ ಸಂಖ್ಯೆ :");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(0, 120, 160, 30);

        txt3.setBackground(new java.awt.Color(51, 255, 0));
        txt3.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        txt3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt3.setOpaque(true);
        jPanel2.add(txt3);
        txt3.setBounds(170, 160, 100, 30);

        jLabel9.setFont(new java.awt.Font("Arial Unicode MS", 1, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 255, 51));
        jLabel9.setText(" ಒಟ್ಟು ತೂಕ :");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(50, 160, 110, 30);

        jLabel10.setFont(new java.awt.Font("Arial Unicode MS", 1, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 255, 51));
        jLabel10.setText(" 1 ಕ್ವಿಂಟಲ್‍ನ ಮೊತ್ತ:");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(0, 200, 170, 30);

        txt4.setBackground(new java.awt.Color(51, 255, 0));
        txt4.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        txt4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt4.setOpaque(true);
        jPanel2.add(txt4);
        txt4.setBounds(170, 200, 100, 30);

        txt5.setBackground(new java.awt.Color(51, 255, 0));
        txt5.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        txt5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt5.setOpaque(true);
        jPanel2.add(txt5);
        txt5.setBounds(170, 240, 100, 30);

        jLabel13.setFont(new java.awt.Font("Arial Unicode MS", 1, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 255, 51));
        jLabel13.setText("ಒಟ್ಟು ಮೊತ್ತ :");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(50, 240, 120, 30);

        jLabel5.setFont(new java.awt.Font("Akshar Unicode", 1, 22)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 204, 0));
        jLabel5.setText("ಮಾರಾಟವಾದ ಉತ್ಪನ್ನದ ಆಯ್ಕೆ");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(60, 0, 205, 40);

        repbtn.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        repbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/rep-icon.png"))); // NOI18N
        repbtn.setText("Genarate Report");
        repbtn.setOpaque(false);
        repbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                repbtnActionPerformed(evt);
            }
        });

        cidlbl.setBackground(new java.awt.Color(51, 255, 0));
        cidlbl.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        cidlbl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cidlbl.setOpaque(true);

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 255, 0));
        jLabel15.setText("ಖಾತೆ ಸಂಖ್ಯೆ :");
        jLabel15.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(repbtn))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cidlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cidlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(repbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(300, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Details", jPanel1);
        jTabbedPane1.addTab("Report", report);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 901, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void csttabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_csttabMouseClicked
        // TODO add your handling code here:
        try {
            int ro=csttab.getSelectedRow();
            cid=csttab.getModel().getValueAt(ro,0).toString();
            cnam=csttab.getModel().getValueAt(ro,1).toString();
            comboCCodes(cid);
            cidlbl.setText(cid);
        }catch(Exception e){}
}//GEN-LAST:event_csttabMouseClicked

    private void csttabKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_csttabKeyPressed
        // TODO add your handling code here:
        int keycode=evt.getKeyCode();
        if(keycode==10) {
            int ro=csttab.getSelectedRow();
            cid=csttab.getModel().getValueAt(ro,0).toString();
            cnam=csttab.getModel().getValueAt(ro,1).toString();
            comboCCodes(cid);
            cidlbl.setText(cid);
        }
}//GEN-LAST:event_csttabKeyPressed

    private void cntxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cntxtKeyPressed
        // TODO add your handling code here:
        int key=evt.getKeyCode();
        if(key==10) {
            csttab.requestFocus();
        }
}//GEN-LAST:event_cntxtKeyPressed
    String sno;
    private void codcmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codcmbActionPerformed
        // TODO add your handling code here:
        String s=(String) codcmb.getSelectedItem();
        if(!s.equals("-Select-"))
        {
            try
            {
                cid=cidlbl.getText();
                String icod=(String) codcmb.getSelectedItem();
                String sts="Closed";
                PrdWiseSrvs pwsrv=new PrdWiseSrvs();
                PrdInvModel pim=null;
                pim=(PrdInvModel)pwsrv.getPrdInvBic(cid, icod, sts);
                txt1.setText(pim.getIname());
                sno =pim.getSlno();
                callaction();
            }catch(Exception e){}
        }
    }//GEN-LAST:event_codcmbActionPerformed

    private void repbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_repbtnActionPerformed
        // TODO add your handling code here:
        
        try {
            MainFrm mf = new MainFrm();
            mf.gentrnrep(cid, cnam);
            String aid=txt2.getText();
            mf.genPrdrep(cid, cnam, aid, sno);
        } catch (Exception ex) {
            Logger.getLogger(FinalRepGen.class.getName()).log(Level.SEVERE, null, ex);
        }
        gentrnrep(cid, cnam);
        String aid=txt2.getText();
        genPrdrep(cid, cnam, aid, sno);
    }//GEN-LAST:event_repbtnActionPerformed
    public void gentrnrep(String cid,String cnam)
    {
        HashMap param=new HashMap();
        String ststus= "Opened";
        param.put("cstid",cid);
        param.put("cname",cnam);
        param.put("sts",ststus);
        try
        {
            File fl=new File("src\\Forms\\Reports\\finalTrn.jrxml");
            String rep=fl.getAbsolutePath();
            FinalTRN repo=new FinalTRN(rep, param);
            repo.setBounds(0, 0, report.getWidth(), report.getHeight());
            repo.setVisible(true);
            this.report.add(repo);
            JOptionPane.showMessageDialog(this, "Transaction Report done");
        }catch(Exception e){JOptionPane.showMessageDialog(this, "Error"+e);}
    }
    public void genPrdrep(String cid,String cnam,String aid,String prdsno)
    {
        HashMap param=new HashMap();
        param.put("cstid",cid);
        param.put("cname",cnam);
        param.put("acid",aid);
        param.put("pslno",prdsno);
        try
        {
            File fl=new File("src\\Forms\\Reports\\Final.jrxml");
            String rep=fl.getAbsolutePath();
            FinalPrd repo=new FinalPrd(rep, param);
            repo.setBounds(0, 0, report.getWidth(), report.getHeight());
            repo.setVisible(true);
            this.report.add(repo);
            JOptionPane.showMessageDialog(this, "Product Report done");
        }catch(Exception e){JOptionPane.showMessageDialog(this, "Error"+e);}
    }
    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        // TODO add your handling code here:
        GETOC.pg=0;
    }//GEN-LAST:event_formInternalFrameClosed
    public void callaction()
    {
        try
        {
            PrdWiseSrvs pwsrv=new PrdWiseSrvs();
            PrdActModel pam=null;
            cid=cidlbl.getText();
            pam=(PrdActModel)pwsrv.getPrdActno(cid,sno);
            txt2.setText(pam.getAid());
            getmore();
        }catch(Exception e){}
    }
    public void getmore()
    {
        try
            {
                PrdWiseSrvs pwsrv=new PrdWiseSrvs();
                CstPrdSellModel psm=null;
                String acid=txt2.getText();
                psm=(CstPrdSellModel)pwsrv.getPrdSellBD(cid, acid);
                txt3.setText(String.valueOf(psm.getPrdwgt()));
                txt4.setText(String.valueOf(psm.getQrate()));
                txt5.setText(String.valueOf(psm.getTotamt()));
                repbtn.setEnabled(true);
            }catch(Exception e){JOptionPane.showMessageDialog(this,"Error"+e);}
    }
    public void comboCCodes(String cid)
    {
        try
        {
            int i=0;
            List lst=null;
            PrdWiseSrvs prdws = new PrdWiseSrvs();
            String sts="Closed";
            lst=(List)prdws.getIcodes(cid, sts);
            String cods[]=new String[lst.size()];
            Iterator itm1=lst.iterator();
            while(itm1.hasNext())
            {
                cods[i]=(String)itm1.next();
                i++;
            }
            codcmb.setModel(new javax.swing.DefaultComboBoxModel(cods));
            codcmb.setMaximumRowCount(6);
            codcmb.setFocusable(true);
        }catch(Exception e){JOptionPane.showMessageDialog(this,"Initialization Failed Please Try Again");}
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cidlbl;
    private javax.swing.JTextField cntxt;
    private javax.swing.JComboBox codcmb;
    private javax.swing.JTable csttab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton repbtn;
    private javax.swing.JDesktopPane report;
    private javax.swing.JLabel txt1;
    private javax.swing.JLabel txt2;
    private javax.swing.JLabel txt3;
    private javax.swing.JLabel txt4;
    private javax.swing.JLabel txt5;
    // End of variables declaration//GEN-END:variables
    Object tabdata[][];
    public void getTableDATA()
    {
        tabdata=null;
        int i=0,j=0;
        CustomerSrvs csr=new CustomerSrvs();
        CstModel cstm=null;
        List lst=new LinkedList();
        lst=(List)csr.getcstTab();
        tabdata=new Object[lst.size()][13];
        String col[]={"ಖಾತೆ ನಂ","ಹೆಸರು"};
        Iterator itm=lst.iterator();
        while(itm.hasNext())
        {
            cstm=(CstModel)itm.next();
            tabdata[i][0]=(String)cstm.getCid();
            tabdata[i][1]=(String)cstm.getCnam();
            i++;
        }
       DefaultTableModel dm =new DefaultTableModel(tabdata,col);
       csttab.setModel(dm);
       csttab.setAutoResizeMode(csttab.AUTO_RESIZE_OFF);
       csttab.getColumnModel().getColumn(0).setPreferredWidth(70);
       csttab.getColumnModel().getColumn(1).setPreferredWidth(130);
    }
}
