/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TRNForm.java
 *
 * Created on Mar 16, 2015, 10:46:37 AM
 */

package Forms;
import APMCMain.GETOC;
import Forms.Models.CstModel;
import Forms.Models.TrnModel;
import Forms.Reports.CRepFrm;
import Forms.Reports.TRepFrm;
import Forms.Services.CustomerSrvs;
import Forms.Services.MasterSrvs;
import Forms.Services.TranSrvs;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import java.io.File;
import java.util.HashMap;
import java.util.Iterator;
import java.util.LinkedList;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.UIManager;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
/**
 *
 * @author user
 */
public class TRNForm extends javax.swing.JInternalFrame {
 Object[][] tabdata;
    /** Creates new form Transaction */
    //TableRowSorter<TableModel> rowSorter = new TableRowSorter<>(csttab.getModel());
    TableRowSorter<TableModel> rowsort;
    /** Creates new form TRNForm */
    String t1,t2,t3,t4,t5,t6;
    double tt5,tt6;
    Double ltot,lramt;


    public TRNForm(){
        super("Transation",false,true,false,true);
        this.setBorder(null);
        initComponents();
        dat.setDate(new java.util.Date());
        MyFont.setUIFont (new javax.swing.plaf.FontUIResource ("Arial Unicode MS",Font.BOLD,16));

        getTableDATA();
        getNamecmb();
        this.setBorder(BorderFactory.createLineBorder(Color.WHITE));this.updateUI();
//-------------------------Seacrh Table String From Text Field------------------------------------------
        rowsort=new TableRowSorter<TableModel>(csttab.getModel());
        csttab.setRowSorter(rowsort);
        cntxt.getDocument().addDocumentListener(new DocumentListener()
        {
            @Override
            public void insertUpdate(DocumentEvent e)
            {
                String text = cntxt.getText();
                if (text.trim().length() == 0)
                {rowsort.setRowFilter(null);}
                else
                {rowsort.setRowFilter(RowFilter.regexFilter("(?i)" + text));}
            }
            @Override
            public void removeUpdate(DocumentEvent e)
            {
                String text = cntxt.getText();
                if (text.trim().length() == 0)
                {rowsort.setRowFilter(null);}
                else
                {rowsort.setRowFilter(RowFilter.regexFilter("(?i)" + text));}
            }
            @Override
            public void changedUpdate(DocumentEvent e)
            {throw new UnsupportedOperationException("Not supported yet.");} //To change body of generated methods, choose Tools | Templates.
        });
        tot.setText("0");
        updatebtn.setEnabled(false);
        savebtn.setEnabled(false);
    }
    public void genRep()
    {
        HashMap param=new HashMap();
        int ro=csttab.getSelectedRow();
        String cid=csttab.getModel().getValueAt(ro,0).toString();
        param.put("custid",cid);
        try
        {
            File fl=new File("src\\Forms\\Reports\\TrnRep.jrxml");
            String rep=fl.getAbsolutePath();
            CRepFrm repo=new CRepFrm(rep, param);
            repo.setBounds(0, 0, dpan.getWidth(), dpan.getHeight());
            repo.setVisible(true);
            this.dpan.add(repo);
        }catch(Exception e){}
    }
    public void genTRep()
    {
        HashMap param=new HashMap();
        String cid=cidtxt.getText();
        String tid=txt1.getText();
        param.put("cstid",cid);
        param.put("trsid",tid);
        try
        {
            File fl=new File("src\\Forms\\Reports\\STrnRep.jrxml");
            String rep=fl.getAbsolutePath();
            TRepFrm repo=new TRepFrm(rep, param);
            repo.setBounds(0, 0, dpan.getWidth(), dpan.getHeight());
            repo.setVisible(true);
            this.dpan.add(repo);
        }catch(Exception e){}
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        csttab = new javax.swing.JTable();
        cntxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        samp = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txt1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dat = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmb4 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        txt3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        addbtn = new javax.swing.JButton();
        savebtn = new javax.swing.JButton();
        updatebtn = new javax.swing.JButton();
        clrbtn = new javax.swing.JButton();
        tot = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cidtxt = new javax.swing.JLabel();
        txt2 = new javax.swing.JLabel();
        samplbl = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        slnocmb = new javax.swing.JComboBox();
        tidcmb = new javax.swing.JComboBox();
        dpan = new javax.swing.JDesktopPane();

        setBackground(new java.awt.Color(59, 0, 59));
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/sanlogo.png"))); // NOI18N
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 0, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        csttab.setBackground(new java.awt.Color(0, 0, 0));
        csttab.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        csttab.setFont(new java.awt.Font("Arial Unicode MS", 1, 20));
        csttab.setForeground(new java.awt.Color(0, 255, 0));
        csttab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "", ""
            }
        ));
        csttab.setGridColor(new java.awt.Color(51, 255, 0));
        csttab.setOpaque(false);
        csttab.setRowHeight(20);
        csttab.setSelectionBackground(new java.awt.Color(51, 255, 0));
        csttab.setSelectionForeground(new java.awt.Color(0, 0, 0));
        csttab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                csttabMouseClicked(evt);
            }
        });
        csttab.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                csttabKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                csttabKeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(csttab);

        cntxt.setBackground(new java.awt.Color(51, 255, 0));
        cntxt.setFont(new java.awt.Font("Akshar Unicode", 1, 20));
        cntxt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        cntxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cntxtKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Fax", 1, 14));
        jLabel1.setForeground(new java.awt.Color(255, 236, 24));
        jLabel1.setText("Type Text Here To Search :-");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cntxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cntxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
                .addContainerGap())
        );

        samp.setBackground(new java.awt.Color(51, 0, 51));
        samp.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel2.setOpaque(false);
        jPanel2.setLayout(null);

        txt1.setBackground(new java.awt.Color(0, 255, 0));
        txt1.setFont(new java.awt.Font("Lucida Bright", 1, 14));
        txt1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt1.setOpaque(true);
        jPanel2.add(txt1);
        txt1.setBounds(150, 60, 60, 22);

        jLabel2.setFont(new java.awt.Font("Arial Unicode MS", 1, 20));
        jLabel2.setForeground(new java.awt.Color(51, 255, 0));
        jLabel2.setText("ವ್ಯವಹಾರಿಕ ಸಂಖ್ಯೆ:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(2, 56, 150, 30);
        jPanel2.add(dat);
        dat.setBounds(319, 58, 112, 20);

        jLabel7.setFont(new java.awt.Font("Arial Unicode MS", 1, 20));
        jLabel7.setForeground(new java.awt.Color(51, 255, 0));
        jLabel7.setText("ದಿನಾಂಕ:");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(244, 58, 63, 20);

        jLabel4.setFont(new java.awt.Font("Arial Unicode MS", 1, 20));
        jLabel4.setForeground(new java.awt.Color(51, 255, 0));
        jLabel4.setText("ಕಾರಣ :");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(421, 15, 70, 20);

        cmb4.setFont(new java.awt.Font("Arial Unicode MS", 1, 20));
        jPanel2.add(cmb4);
        cmb4.setBounds(489, 13, 265, 25);

        jLabel5.setFont(new java.awt.Font("Arial Unicode MS", 1, 20));
        jLabel5.setForeground(new java.awt.Color(51, 255, 0));
        jLabel5.setText("ಹಣ :");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(433, 58, 50, 20);

        txt3.setFont(new java.awt.Font("Tunga", 1, 16));
        txt3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txt3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt3KeyPressed(evt);
            }
        });
        jPanel2.add(txt3);
        txt3.setBounds(489, 56, 88, 27);

        jLabel6.setFont(new java.awt.Font("Arial Unicode MS", 1, 20));
        jLabel6.setForeground(new java.awt.Color(51, 255, 0));
        jLabel6.setText("ರೂ ಮಾತ್ರ/-");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(581, 59, 100, 20);

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel4.setOpaque(false);

        addbtn.setFont(new java.awt.Font("Times New Roman", 1, 14));
        addbtn.setForeground(new java.awt.Color(19, 68, 8));
        addbtn.setText("ADD NEW");
        addbtn.setDoubleBuffered(true);
        addbtn.setOpaque(false);
        addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });

        savebtn.setFont(new java.awt.Font("Times New Roman", 1, 14));
        savebtn.setForeground(new java.awt.Color(19, 68, 8));
        savebtn.setText("SAVE");
        savebtn.setDoubleBuffered(true);
        savebtn.setOpaque(false);
        savebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebtnActionPerformed(evt);
            }
        });
        savebtn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                savebtnKeyPressed(evt);
            }
        });

        updatebtn.setFont(new java.awt.Font("Times New Roman", 1, 14));
        updatebtn.setForeground(new java.awt.Color(19, 68, 8));
        updatebtn.setText("UPDATE");
        updatebtn.setDoubleBuffered(true);
        updatebtn.setOpaque(false);
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });

        clrbtn.setFont(new java.awt.Font("Times New Roman", 1, 14));
        clrbtn.setForeground(new java.awt.Color(19, 68, 8));
        clrbtn.setText("CLEAR");
        clrbtn.setDoubleBuffered(true);
        clrbtn.setOpaque(false);
        clrbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clrbtnActionPerformed(evt);
            }
        });

        tot.setBackground(new java.awt.Color(0, 255, 0));
        tot.setFont(new java.awt.Font("Lucida Bright", 1, 14));
        tot.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tot.setOpaque(true);

        jLabel8.setFont(new java.awt.Font("Arial Unicode MS", 1, 20));
        jLabel8.setForeground(new java.awt.Color(51, 255, 0));
        jLabel8.setText("ವ್ಯವಹಾರಿದ ಒಟ್ಟು ಮೊತ್ತ :");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(savebtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(updatebtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clrbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(tot, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(addbtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(savebtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(updatebtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(clrbtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(tot, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2.add(jPanel4);
        jPanel4.setBounds(12, 94, 742, 50);

        cidtxt.setBackground(new java.awt.Color(0, 255, 0));
        cidtxt.setFont(new java.awt.Font("Lucida Bright", 1, 14));
        cidtxt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cidtxt.setOpaque(true);
        jPanel2.add(cidtxt);
        cidtxt.setBounds(147, 13, 80, 22);

        txt2.setBackground(new java.awt.Color(0, 255, 0));
        txt2.setFont(new java.awt.Font("Lucida Bright", 1, 14));
        txt2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt2.setOpaque(true);
        jPanel2.add(txt2);
        txt2.setBounds(320, 10, 60, 20);

        samplbl.setFont(new java.awt.Font("Arial Unicode MS", 1, 20));
        samplbl.setForeground(new java.awt.Color(51, 255, 0));
        samplbl.setText("ಖಾತೆ ಸಂಖ್ಯೆ:");
        jPanel2.add(samplbl);
        samplbl.setBounds(41, 13, 110, 22);

        jLabel3.setFont(new java.awt.Font("Arial Unicode MS", 1, 20));
        jLabel3.setForeground(new java.awt.Color(51, 255, 0));
        jLabel3.setText("ಕ್ರಂ ಸಂಖ್ಯೆ:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(232, 13, 90, 20);

        slnocmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                slnocmbActionPerformed(evt);
            }
        });
        jPanel2.add(slnocmb);
        slnocmb.setBounds(320, 10, 80, 20);

        tidcmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tidcmbActionPerformed(evt);
            }
        });
        jPanel2.add(tidcmb);
        tidcmb.setBounds(150, 60, 80, 20);

        javax.swing.GroupLayout sampLayout = new javax.swing.GroupLayout(samp);
        samp.setLayout(sampLayout);
        sampLayout.setHorizontalGroup(
            sampLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sampLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 766, Short.MAX_VALUE)
                .addContainerGap())
        );
        sampLayout.setVerticalGroup(
            sampLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sampLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dpan.setBackground(new java.awt.Color(59, 0, 59));
        dpan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dpan, javax.swing.GroupLayout.DEFAULT_SIZE, 790, Short.MAX_VALUE)
                    .addComponent(samp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(dpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(samp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void csttabKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_csttabKeyPressed
        // TODO add your handling code here:
        int keycode=evt.getKeyCode();
        if(keycode==10) {
            dpan.removeAll();
            dpan.repaint();
            genRep();
            int ro=csttab.getSelectedRow();
            t1=csttab.getModel().getValueAt(ro,0).toString();
            cidtxt.setText(t1);
            getNextTid();
            comboTIDs(t1);
            savebtn.setEnabled(true);
        }
}//GEN-LAST:event_csttabKeyPressed

    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtnActionPerformed
        // TODO add your handling code here:
       // getNextTid();
        int reply = JOptionPane.showConfirmDialog(null, "ಹೊಸ ವ್ಯವಹಾರಿಕ ಸಂಖ್ಯೆಯೊಂದಿಗೆ ಮುಂದುವರೆಯುವಿರ ?", "ವ್ಯವಹಾರಿಕ ಸಂಖ್ಯೆ", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
          getNextTid();
        }
        else
        {
            clrall();
            savebtn.setEnabled(true);
        }
        
}//GEN-LAST:event_addbtnActionPerformed
    public void comboTIDs(String cid)
    {
        try
        {
        int i=0;
        List lst=null;
        TranSrvs tsr=new TranSrvs();
        lst=(List)tsr.gettid(cid);
        String cods[]=new String[lst.size()];
        Iterator itm1=lst.iterator();
        while(itm1.hasNext())
        {
             cods[i]=(String)itm1.next();
             i++;
        }
        tidcmb.setModel(new javax.swing.DefaultComboBoxModel(cods));
        tidcmb.setMaximumRowCount(6);
        tidcmb.setFocusable(true);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,"Initialization Failed Please Try Again");
        }
    }
    public void clrall()
    {
        cmb4.setSelectedIndex(0);
        txt3.setText("");
        dat.setDate(new java.util.Date());
    }
    public void getNextTid()
    {
        TranSrvs tsr=new TranSrvs();
        List ls=null;
        String cid=cidtxt.getText();
        ls= tsr.getNextTId(cid);
        int cod=ls.size();
        int nex=cod+1;
        txt1.setText("T"+nex);
        nxtslno();
    }
    public void nxtslno()
    {
        TranSrvs tsr=new TranSrvs();
        List ls=null;
        String cid=cidtxt.getText();
        String tid=txt1.getText();
        ls= tsr.getNextTSlno(cid,tid);
        int cod=ls.size();
        int nex=cod+1;
        txt2.setText(String.valueOf(nex));

    }
    private void savebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtnActionPerformed
        // TODO add your handling code here:
        
        t1=cidtxt.getText();
        t2=txt1.getText();
        t3=txt2.getText().trim();
        t4=(String) cmb4.getSelectedItem();
        t5=txt3.getText();
        t6=tot.getText();
        boolean vlt=validtrn();
        if(vlt)
        {
            java.sql.Date td=new java.sql.Date(dat.getDate().getTime());
            boolean flag=false;
            TranSrvs trs=new TranSrvs();
            flag=trs.saveTrn(t1, t2, t3, td, t4, tt5, tt6);
            if(flag)
            {
                updateamt();
            }else{JOptionPane.showMessageDialog(this, "ಕ್ಷಮಿಸಿ ವ್ಯವಹಾರಿಕ ವಿವರಗಳನ್ನು ಉಳಿಸಲು ಸಾದ್ಯವಾಗುತ್ತಿಲ್ಲಾ");}
        }
            

}//GEN-LAST:event_savebtnActionPerformed
    public void updateamt()
    {
        boolean flag=false;
        TranSrvs trs=new TranSrvs();
        Double ta=Double.valueOf(tot.getText());
        flag=trs.UpdateAMT(t1,t2,ta);
        if(flag)
        {
            dpan.removeAll();
            dpan.repaint();
            genTRep();
            nxtslno();
            JOptionPane.showMessageDialog(this, "ವ್ಯವಹಾರಿಕ ವಿವರಗಳನ್ನು ಉಳಿಸಲಾಗಿದೆ");
            cmb4.setSelectedIndex(0);
            txt3.setText("");
        }else{JOptionPane.showMessageDialog(this, "ಒಟ್ಟು ಮೊತ್ತ ಉಳಿಸಲು ಸಾದ್ಯವಾಗುತ್ತಿಲ್ಲ");}
    }

    private boolean validtrn()
    {
        try{
        if(t1.length()==0){JOptionPane.showMessageDialog(this, "ದಯವಿಟ್ಟು ಖಾತೆಯನ್ನು ಖಾತೆ ಪಟ್ಟಿಯಿಂದ ಆಯ್ದು ಕೊಳ್ಳಿ");return false;}
        if(t3.length()==0){JOptionPane.showMessageDialog(this, "ದಯವಿಟ್ಟು ವ್ಯವಹಾರಿಕ ಸಂಖ್ಯೆಯನ್ನು ಆಯ್ದು ಕೊಳ್ಳಿ");return false;}
        if(t4.length()==0){JOptionPane.showMessageDialog(this, "ದಯವಿಟ್ಟು ಕಾರಣವನ್ನು ಆಯ್ದು ಕೊಳ್ಳಿ");return false;}
        if(t5.length()==0){JOptionPane.showMessageDialog(this, "ದಯವಿಟ್ಟು ಹಣವನ್ನು ನಮೊದಿಸಿ");return false;}
        try{tt5=Double.valueOf(t5);}catch(Exception e){JOptionPane.showMessageDialog(this, "ದಯವಿಟ್ಟು ಹಣವನ್ನು ಸಂಖ್ಯೆಗಳಲ್ಲಿ ನಮೊದಿಸಿ");return false;}}
        catch(Exception e){JOptionPane.showMessageDialog(this, e);}
        return true;
    }
    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
        t1=cidtxt.getText();
        t2=txt1.getText();
        t3=txt2.getText().trim();
        t4=(String) cmb4.getSelectedItem();
        t5=txt3.getText();
        t6=tot.getText();
        boolean vlt=validtrn();
        if(vlt)
        {
            Double clst=ltot-lramt;
            Double sna=clst+tt5;
            tot.setText(String.valueOf(sna));
            boolean flg=false;
            TranSrvs trs=new TranSrvs();
            flg=trs.UpdateTrn(t1, t2, t3, t4, tt5);
            if(flg)
            {
                updateamt();
            }else{JOptionPane.showMessageDialog(this, "ಕ್ಷಮಿಸಿ ವ್ಯವಹಾರಿಕ ವಿವರಗಳನ್ನು ಉಳಿಸಲು ಸಾದ್ಯವಾಗುತ್ತಿಲ್ಲಾ");}
        }
}//GEN-LAST:event_updatebtnActionPerformed

    private void clrbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clrbtnActionPerformed
        // TODO add your handling code here:
         clrall();
}//GEN-LAST:event_clrbtnActionPerformed

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        // TODO add your handling code here:
        GETOC.t1=0;
    }//GEN-LAST:event_formInternalFrameClosed

    private void tidcmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tidcmbActionPerformed
        // TODO add your handling code here:
        String id=(String) tidcmb.getSelectedItem();
        if(!id.equals("-Select-"))
        {
            try
            {
                t1=cidtxt.getText();
                t2=(String) tidcmb.getSelectedItem();
                txt1.setText((String) tidcmb.getSelectedItem());
                comboSlo(t1,t2);
                settot();
                nxtslno();
                dpan.removeAll();
                dpan.repaint();
                genTRep();
            }catch(Exception e){}
        }
    }//GEN-LAST:event_tidcmbActionPerformed
    public void settot()
    {
        TranSrvs tsr=new TranSrvs();
        TrnModel tm=null;
        String cid=cidtxt.getText();
        String tid=(String) tidcmb.getSelectedItem();
        tm=(TrnModel)tsr.getTData(cid,tid);
        tot.setText(String.valueOf(tm.getTotamt()));
    }
    private void slnocmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_slnocmbActionPerformed
        // TODO add your handling code here:
        String id=(String) slnocmb.getSelectedItem();
        if(!id.equals("-Select-"))
        {
            try
            {
                TranSrvs tsr=new TranSrvs();
                TrnModel trm=null;
                t1=cidtxt.getText();
                t2=txt1.getText();
                t3=(String) slnocmb.getSelectedItem();
                trm=(TrnModel)tsr.TDataBySLNO(t1,t2,t3);
                java.util.Date d=new java.util.Date();
                d=trm.getTdat();
                dat.setDate(d);
                txt2.setText(trm.getSlno());
                cmb4.setSelectedItem(trm.getReason());
                txt3.setText(String.valueOf(trm.getAmt()));
                ltot=trm.getTotamt();
                lramt=trm.getAmt();
                savebtn.setEnabled(false);
                updatebtn.setEnabled(true);
            }catch(Exception e){}
        }
    }//GEN-LAST:event_slnocmbActionPerformed

    private void cntxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cntxtKeyPressed
        // TODO add your handling code here:
        int key=evt.getKeyCode();
        if(key==10)
        {
            csttab.requestFocus();
        }
    }//GEN-LAST:event_cntxtKeyPressed

    private void txt3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt3KeyPressed
        // TODO add your handling code here:
        int k=evt.getKeyCode();
        if(k==10)
        {
            try{
            Double t=Double.valueOf(tot.getText());
            Double at=Double.valueOf(txt3.getText());
            Double add=t+at;
            tot.setText(String.valueOf(add));
            savebtn.requestFocus();}catch(Exception e){JOptionPane.showMessageDialog(this, "Enter No Please");txt3.requestFocus();}
        }
    }//GEN-LAST:event_txt3KeyPressed

    private void savebtnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_savebtnKeyPressed
        // TODO add your handling code here:
        int k=evt.getKeyCode();
        if(k==10)
        {
        savebtn.doClick();
        }
    }//GEN-LAST:event_savebtnKeyPressed

    private void csttabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_csttabMouseClicked
        // TODO add your handling code here:
        try{
        dpan.removeAll();
            dpan.repaint();
            genRep();
            int ro=csttab.getSelectedRow();
            t1=csttab.getModel().getValueAt(ro,0).toString();
            cidtxt.setText(t1);
            getNextTid();
            comboTIDs(t1);
            savebtn.setEnabled(true);
        }catch(Exception e){}
    }//GEN-LAST:event_csttabMouseClicked

    private void csttabKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_csttabKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_csttabKeyReleased
    public void comboSlo(String cid,String tid)
    {
        try
        {
        int i=0;
        List lst=null;
        TranSrvs tsr=new TranSrvs();
        lst=(List)tsr.Getslno(cid,tid);
        String cods[]=new String[lst.size()];
        Iterator itm1=lst.iterator();
        while(itm1.hasNext())
        {
             cods[i]=(String)itm1.next();
             i++;
        }
        slnocmb.setModel(new javax.swing.DefaultComboBoxModel(cods));
        slnocmb.setMaximumRowCount(6);
        slnocmb.setFocusable(true);
        }catch(Exception e){JOptionPane.showMessageDialog(this,"Initialization Failed Please Try Again");}
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbtn;
    private javax.swing.JLabel cidtxt;
    private javax.swing.JButton clrbtn;
    private javax.swing.JComboBox cmb4;
    private javax.swing.JTextField cntxt;
    private javax.swing.JTable csttab;
    private com.toedter.calendar.JDateChooser dat;
    private javax.swing.JDesktopPane dpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel samp;
    private javax.swing.JLabel samplbl;
    private javax.swing.JButton savebtn;
    private javax.swing.JComboBox slnocmb;
    private javax.swing.JComboBox tidcmb;
    private javax.swing.JLabel tot;
    private javax.swing.JLabel txt1;
    private javax.swing.JLabel txt2;
    private javax.swing.JTextField txt3;
    private javax.swing.JButton updatebtn;
    // End of variables declaration//GEN-END:variables
     public void getTableDATA()
    {
        int i=0,j=0;
        CustomerSrvs csr=new CustomerSrvs();
        CstModel cstm=null;
        List lst=new LinkedList();
        lst=(List)csr.getcstTab();
        tabdata=new Object[lst.size()][13];
        String col[]={"ಖಾತೆ ನಂ","ಹೆಸರು"};
        Iterator itm=lst.iterator();
        while(itm.hasNext())
        {
            cstm=(CstModel)itm.next();
            tabdata[i][0]=(String)cstm.getCid();
            tabdata[i][1]=(String)cstm.getCnam();
            i++;
        }
       DefaultTableModel dm =new DefaultTableModel(tabdata,col);
       csttab.setModel(dm);
       csttab.setAutoResizeMode(csttab.AUTO_RESIZE_OFF);
       csttab.getColumnModel().getColumn(0).setPreferredWidth(70);
       csttab.getColumnModel().getColumn(1).setPreferredWidth(130);
    }
     public void getNamecmb()//getIDcmb()
    {
        int i=0;
        List lst=null;
        MasterSrvs msrv=new MasterSrvs();
        lst=msrv.getSlnocmb();
        String per[]=new String[lst.size()];
        Iterator itm1=lst.iterator();
        while(itm1.hasNext())
        {
            per[i]=(String)itm1.next();
            i++;
        }
        cmb4.setModel(new javax.swing.DefaultComboBoxModel(per));
        cmb4.setMaximumRowCount(6);
        cmb4.setFocusable(true);
   }
    
}
