/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CustomerReg.java
 *
 * Created on Mar 3, 2015, 11:14:03 AM
 */

package APMCMain;
import APMCMain.MainFrm;
import Forms.CstReport;
import Forms.CustReg;
import Forms.Master;
import Forms.MyFont;
import Forms.Payment;
import Forms.Reports.FinalPrd;
import Forms.Reports.FinalTRN;
import Forms.TRNForm;
import Forms.TrnReport;
import java.awt.*;
import java.io.File;
import javax.swing.UIManager;
import java.io.IOException;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/*
 *
 * @author user
 */
public class MainFrm extends javax.swing.JFrame {
    int cst=0,trn=0;
    
    /** Creates new form CustomerReg */
    public MainFrm() throws IOException {
        initComponents();
        this.setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);
        MyFont.setUIFont (new javax.swing.plaf.FontUIResource ("Arial Unicode MS",Font.BOLD,16));
        this.setIconImage(Toolkit.getDefaultToolkit().getImage("src\\Admin\\Authentication\\1.png"));
        entrybtn.setEnabled(false);
        searchbtn.setEnabled(false);
        repbtn.setEnabled(false);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        trnbtn = new javax.swing.JButton();
        admbtn = new javax.swing.JButton();
        mstbtn = new javax.swing.JButton();
        paybtn = new javax.swing.JButton();
        ctmbtn = new javax.swing.JButton();
        MainPan = new javax.swing.JDesktopPane();
        jPanel2 = new javax.swing.JPanel();
        searchbtn = new javax.swing.JButton();
        repbtn = new javax.swing.JButton();
        entrybtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.white);

        jPanel1.setBackground(new java.awt.Color(69, 6, 69));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton1.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/hom.png"))); // NOI18N
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jButton3.setText("Close ALL");
        jButton3.setOpaque(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        trnbtn.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        trnbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/trn.png"))); // NOI18N
        trnbtn.setText("Transaction");
        trnbtn.setOpaque(false);
        trnbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trnbtnActionPerformed(evt);
            }
        });

        admbtn.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        admbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/admin.png"))); // NOI18N
        admbtn.setText("Settings");
        admbtn.setOpaque(false);

        mstbtn.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        mstbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/master.png"))); // NOI18N
        mstbtn.setText("Master");
        mstbtn.setOpaque(false);
        mstbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mstbtnActionPerformed(evt);
            }
        });

        paybtn.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        paybtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/pay.png"))); // NOI18N
        paybtn.setText("Payment");
        paybtn.setOpaque(false);
        paybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paybtnActionPerformed(evt);
            }
        });

        ctmbtn.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        ctmbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/cst.png"))); // NOI18N
        ctmbtn.setText("Customer");
        ctmbtn.setOpaque(false);
        ctmbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctmbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ctmbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(trnbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paybtn, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mstbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(admbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 178, Short.MAX_VALUE)
                .addComponent(jButton3))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(ctmbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(trnbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                .addComponent(paybtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, Short.MAX_VALUE)
                .addComponent(mstbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addComponent(admbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, Short.MAX_VALUE))
            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
        );

        MainPan.setBackground(new java.awt.Color(69, 6, 69));
        MainPan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jPanel2.setBackground(new java.awt.Color(69, 6, 69));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        searchbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/dbview.png"))); // NOI18N
        searchbtn.setOpaque(false);

        repbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/dbreport.png"))); // NOI18N
        repbtn.setOpaque(false);
        repbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                repbtnActionPerformed(evt);
            }
        });

        entrybtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/dbadd.png"))); // NOI18N
        entrybtn.setOpaque(false);
        entrybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrybtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ENTRY");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("REPORT");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("  SEARCH");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(repbtn, 0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1))
                    .addComponent(entrybtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, Short.MAX_VALUE)
                    .addComponent(searchbtn, 0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(entrybtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(23, 23, 23)
                .addComponent(repbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(272, 272, 272))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MainPan, javax.swing.GroupLayout.DEFAULT_SIZE, 1009, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE)
                    .addComponent(MainPan, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void ctmbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctmbtnActionPerformed
        // TODO add your handling code here:
        entrybtn.setEnabled(true);
        searchbtn.setEnabled(true);
        repbtn.setEnabled(true);
        cst=1;
        ctmbtn.setEnabled(false);
        trnbtn.setEnabled(true);
        trn=0;
    }//GEN-LAST:event_ctmbtnActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            // TODO add your handling code here:
            clsctm();
        } catch (IOException ex) {
            Logger.getLogger(MainFrm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void trnbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trnbtnActionPerformed
        // TODO add your handling code here:
        entrybtn.setEnabled(true);
        searchbtn.setEnabled(true);
        repbtn.setEnabled(true);
        cst=0;
        ctmbtn.setEnabled(true);
        trnbtn.setEnabled(false);
        trn=1;
    }//GEN-LAST:event_trnbtnActionPerformed

    private void entrybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrybtnActionPerformed
        // TODO add your handling code here:
        if(cst==1)
        {   CustReg csm=null;
            try {
                csm = new CustReg();
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "Image Not Found Exception"+ex);
            }
            if(GETOC.c1==0)
            {
            try
            {
                csm.setVisible(false);
                csm.setBounds(0, 0, 1104, 508);//[1104, 508]
                csm.setVisible(true);
                MainPan.add(csm);
                GETOC.c1=1;
                csm.requestFocus();
            }catch(Exception e){}
            }
        }
        if(trn==1)
        {
            TRNForm trs = new TRNForm();
            if(GETOC.t1==0)
            {
            try
            {
                trs.setVisible(false);
                trs.setBounds(0, 0, 1110, 684);//[1078, 673]
                trs.setVisible(true);
                MainPan.add(trs);
                GETOC.t1=1;
                trs.requestFocus();
            }catch(Exception e){}
            }
        }
    }//GEN-LAST:event_entrybtnActionPerformed
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            clsctm();
        } catch (IOException ex) {
            Logger.getLogger(MainFrm.class.getName()).log(Level.SEVERE, null, ex);
        }
        cst=0;
        trn=0;
        ctmbtn.setEnabled(true);
        trnbtn.setEnabled(true);
        entrybtn.setEnabled(false);
        searchbtn.setEnabled(false);
        repbtn.setEnabled(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void mstbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mstbtnActionPerformed
        // TODO add your handling code here:
        Master mst=new Master();
        if(GETOC.m==0)
            {
            try
            {
                mst.setVisible(false);
                int h=MainPan.getHeight();
                int w=MainPan.getWidth();
                mst.setBounds(0, 0, w,h);//[1072, 707]
                mst.setVisible(true);
                MainPan.add(mst);
                mst.setVisible(true);
                GETOC.m=1;
                mst.requestFocus();
            }catch(Exception e){}
            }
    }//GEN-LAST:event_mstbtnActionPerformed

    private void paybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paybtnActionPerformed
        // TODO add your handling code here:
        Payment pay=new Payment();
        if(GETOC.p==0)
            {
            try
            {
                pay.setVisible(false);
                int h=MainPan.getHeight();
                int w=MainPan.getWidth();
                pay.setBounds(0, 0, w,h);//[1072, 707]
                pay.setVisible(true);
                MainPan.add(pay);
                pay.setVisible(true);
                GETOC.p=1;
                pay.requestFocus();
            }catch(Exception e){}
            }
    }//GEN-LAST:event_paybtnActionPerformed

    private void repbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_repbtnActionPerformed
        // TODO add your handling code here:
        if(cst==1)
        {
            CstReport cr = new CstReport();
            if(GETOC.c3==0)
            {
            try
            {
                cr.setVisible(false);
                int h=MainPan.getHeight();
                int w=MainPan.getWidth();
                cr.setBounds(0, 0, w, h);//[1104, 508]
                cr.setVisible(true);
                MainPan.add(cr);
                GETOC.c3=1;
                cr.requestFocus();
            }catch(Exception e){}
            }
        }
        if(trn==1)
        {
            TrnReport trs = new TrnReport();
            if(GETOC.t3==0)
            {
            try
            {
                trs.setVisible(false);
                int h=MainPan.getHeight();
                int w=MainPan.getWidth();
                trs.setBounds(0, 0, w, h);//[1078, 673]
                trs.setVisible(true);
                MainPan.add(trs);
                GETOC.t3=1;
                trs.requestFocus();
            }catch(Exception e){}
            }
        }
    }//GEN-LAST:event_repbtnActionPerformed
    public void clsctm() throws IOException
    {
        MainPan.removeAll();
        MainPan.repaint();
        GETOC.c1=0;
        GETOC.c2=0;
        GETOC.c3=0;
        GETOC.t1=0;
        GETOC.t2=0;
        GETOC.t3=0;
        GETOC.m=0;
        GETOC.mr=0;  
    }
    public void gentrnrep(String cid,String cnam)
    {
        HashMap param=new HashMap();
        String ststus= "Opened";
        param.put("cstid",cid);
        param.put("cname",cnam);
        param.put("sts",ststus);
        try
        {
            File fl=new File("src\\Forms\\Reports\\finalTrn.jrxml");
            String rep=fl.getAbsolutePath();
            FinalTRN repo=new FinalTRN(rep, param);
           // repo.setBounds(0, 0, MainPan.getWidth(), MainPan.getHeight());
            repo.setVisible(true);
          //  this.MainPan.add(repo);
            JOptionPane.showMessageDialog(this, "Transaction Report done");
        }catch(Exception e){JOptionPane.showMessageDialog(this, "Error"+e);}
    }
    public void genPrdrep(String cid,String cnam,String aid,String prdsno)
    {
        HashMap param=new HashMap();
        param.put("cstid",cid);
        param.put("cname",cnam);
        param.put("acid",aid);
        param.put("pslno",prdsno);
        try
        {
            File fl=new File("src\\Forms\\Reports\\Final.jrxml");
            String rep=fl.getAbsolutePath();
            FinalPrd repo=new FinalPrd(rep, param);
            repo.setBounds(0, 0, MainPan.getWidth(), MainPan.getHeight());
            repo.setVisible(true);
            this.MainPan.add(repo);
            JOptionPane.showMessageDialog(this, "Product Report done");
        }catch(Exception e){JOptionPane.showMessageDialog(this, "Error"+e);}
    }

    
  //-------------------Mac Style Designing---------------------------------------------
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() 
        {public void run()
         {try
          {try
           {
               UIManager.setLookAndFeel("com.jtattoo.plaf.mcwin.McWinLookAndFeel");
           }catch(Exception ex){JOptionPane.showMessageDialog(null, "Error is ="+ex);}
           new MainFrm().setVisible(true);
          }catch(IOException ex){Logger.getLogger(MainFrm.class.getName()).log(Level.SEVERE, null, ex);}
         }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JDesktopPane MainPan;
    private javax.swing.JButton admbtn;
    private javax.swing.JButton ctmbtn;
    private javax.swing.JButton entrybtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton mstbtn;
    private javax.swing.JButton paybtn;
    private javax.swing.JButton repbtn;
    private javax.swing.JButton searchbtn;
    private javax.swing.JButton trnbtn;
    // End of variables declaration//GEN-END:variables
   
    
}
