/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Message.java
 *
 * Created on 1 Jan, 2015, 12:41:06 PM
 */

package Sales;

import Sales.model.Goldcst_model;
import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.sql.Date;
import java.util.Iterator;
import java.util.LinkedList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Dell-PC
 */
public class Messaging extends javax.swing.JPanel {
    //attrib for shadow starts************************************************
    protected int strokeSize = 1;
    protected Color shadowColor = Color.black;
    protected boolean shady = true;
    protected boolean highQuality = true;
    protected Dimension arcs = new Dimension(20, 20);
    protected int shadowGap = 5;
    protected int shadowOffset = 4;
    protected int shadowAlpha = 150;
//attrib for shadow stops************************************************
    /** Creates new form Message */
    String t1,t2,t3,t4;
    public Messaging() {
        initComponents();
        comboSCustIDs();
        comboGCustIDs();
        today.setDate(new java.util.Date());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    Sales.Services.Goldservices gs=new Sales.Services.Goldservices();

    public void comboGCustIDs()
    {
        try
        {
        int i=0;
        List lst=null;
        lst=(List)gs.getcustid();
        String cods[]=new String[lst.size()];
        Iterator itm1=lst.iterator();
        while(itm1.hasNext())
        {
             cods[i]=(String)itm1.next();
             i++;
        }
        gcmb.setModel(new javax.swing.DefaultComboBoxModel(cods));
        gcmb.setMaximumRowCount(6);
        gcmb.setFocusable(true);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,"Initialization Failed Please Try Again");
        }
    }
    public void comboSCustIDs()
    {
        try
        {
        int i=0;
        List lst=null;
        lst=(List)gs.getcustid();
        String cods[]=new String[lst.size()];
        Iterator itm1=lst.iterator();
        while(itm1.hasNext())
        {
             cods[i]=(String)itm1.next();
             i++;
        }
        scmb.setModel(new javax.swing.DefaultComboBoxModel(cods));
        scmb.setMaximumRowCount(3);
        scmb.setFocusable(true);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,"Initialization Failed Please Try Again");
        }
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabpan = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        mgt5 = new javax.swing.JTextField();
        gct2 = new javax.swing.JScrollPane();
        mgt3 = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        mgt2 = new javax.swing.JTextField();
        mgt4 = new javax.swing.JTextField();
        gcmb = new javax.swing.JComboBox();
        trsid = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        mgt6 = new javax.swing.JTextField();
        mgt7 = new javax.swing.JTextField();
        mgt8 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        mgtab = new javax.swing.JTable();
        jLabel27 = new javax.swing.JLabel();
        mgclearbtn = new javax.swing.JButton();
        datelbl = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        mst5 = new javax.swing.JTextField();
        gct8 = new javax.swing.JScrollPane();
        mst3 = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        mst2 = new javax.swing.JTextField();
        mst4 = new javax.swing.JTextField();
        scmb = new javax.swing.JComboBox();
        jPanel7 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        mst6 = new javax.swing.JTextField();
        mst7 = new javax.swing.JTextField();
        mst8 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        mstab = new javax.swing.JTable();
        msclearbtn = new javax.swing.JButton();
        sdatelbl = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        mgclosebtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        mtxt = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        today = new com.toedter.calendar.JDateChooser();

        setOpaque(false);

        tabpan.setFont(new java.awt.Font("Times New Roman", 1, 14));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Personal_details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N
        jPanel3.setFont(new java.awt.Font("Times New Roman", 1, 14));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel2.setText(" Customer id:");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel3.setText("Address :");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel4.setText("City :");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel5.setText("Phone_no:");

        mgt5.setFont(new java.awt.Font("Times New Roman", 1, 14));
        mgt5.setText(" ");
        mgt5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mgt5.setEnabled(false);
        mgt5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mgt5KeyPressed(evt);
            }
        });

        gct2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                gct2KeyPressed(evt);
            }
        });

        mgt3.setBackground(new java.awt.Color(240, 240, 240));
        mgt3.setColumns(20);
        mgt3.setFont(new java.awt.Font("Times New Roman", 1, 14));
        mgt3.setRows(5);
        mgt3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mgt3.setEnabled(false);
        mgt3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mgt3KeyPressed(evt);
            }
        });
        gct2.setViewportView(mgt3);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel15.setText(" Name :");

        mgt2.setFont(new java.awt.Font("Times New Roman", 1, 14));
        mgt2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mgt2.setEnabled(false);
        mgt2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mgt2KeyPressed(evt);
            }
        });

        mgt4.setFont(new java.awt.Font("Times New Roman", 1, 14));
        mgt4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mgt4.setEnabled(false);
        mgt4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mgt4KeyPressed(evt);
            }
        });

        gcmb.setFont(new java.awt.Font("Times New Roman", 1, 14));
        gcmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gcmbActionPerformed(evt);
            }
        });

        trsid.setFont(new java.awt.Font("Times New Roman", 1, 14));
        trsid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trsidActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel10.setText("Transaction ID:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel15)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mgt5, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(gcmb, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(trsid, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(gct2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(mgt2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mgt4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gcmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(trsid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(mgt2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(gct2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(mgt4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mgt5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Payment", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel12.setText("Total Amount:");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel13.setText("Paid:");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel14.setText(" Balance:");

        mgt6.setFont(new java.awt.Font("Times New Roman", 1, 14));
        mgt6.setText(" ");
        mgt6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mgt6.setEnabled(false);
        mgt6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mgt6KeyPressed(evt);
            }
        });

        mgt7.setFont(new java.awt.Font("Times New Roman", 1, 14));
        mgt7.setText(" ");
        mgt7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mgt7.setEnabled(false);
        mgt7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mgt7KeyPressed(evt);
            }
        });

        mgt8.setFont(new java.awt.Font("Times New Roman", 1, 14));
        mgt8.setText(" ");
        mgt8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mgt8.setEnabled(false);
        mgt8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mgt8KeyPressed(evt);
            }
        });

        mgtab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        mgtab.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mgtabKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(mgtab);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(mgt6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(mgt7, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(mgt8, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(mgt6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(mgt7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(mgt8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jLabel27.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel27.setText("Purchased Date:");

        mgclearbtn.setFont(new java.awt.Font("Lucida Sans", 1, 14));
        mgclearbtn.setText("Reset");
        mgclearbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mgclearbtnActionPerformed(evt);
            }
        });
        mgclearbtn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mgclearbtnKeyPressed(evt);
            }
        });

        datelbl.setFont(new java.awt.Font("Times New Roman", 1, 14));
        datelbl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(mgclearbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(datelbl, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                                    .addComponent(jLabel27))))))
                .addGap(16, 16, 16))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(datelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(mgclearbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tabpan.addTab(" Gold_Sale", jPanel1);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Personal_details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N
        jPanel4.setFont(new java.awt.Font("Times New Roman", 1, 14));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel6.setText(" Customer id:");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel7.setText("Address :");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel8.setText("City :");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel9.setText("Phone_no:");

        mst5.setFont(new java.awt.Font("Times New Roman", 1, 14));
        mst5.setText(" ");
        mst5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mst5.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        mst5.setEnabled(false);
        mst5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mst5KeyPressed(evt);
            }
        });

        gct8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                gct8KeyPressed(evt);
            }
        });

        mst3.setBackground(new java.awt.Color(240, 240, 240));
        mst3.setColumns(20);
        mst3.setFont(new java.awt.Font("Times New Roman", 1, 14));
        mst3.setRows(5);
        mst3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mst3.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        mst3.setEnabled(false);
        mst3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mst3KeyPressed(evt);
            }
        });
        gct8.setViewportView(mst3);

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel16.setText(" Name :");

        mst2.setFont(new java.awt.Font("Times New Roman", 1, 14));
        mst2.setText(" ");
        mst2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mst2.setDisabledTextColor(new java.awt.Color(0, 51, 51));
        mst2.setEnabled(false);
        mst2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mst2KeyPressed(evt);
            }
        });

        mst4.setFont(new java.awt.Font("Times New Roman", 1, 14));
        mst4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mst4.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        mst4.setEnabled(false);

        scmb.setFont(new java.awt.Font("Times New Roman", 1, 14));
        scmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scmbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scmb, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mst2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gct8, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                            .addComponent(mst4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mst5, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(scmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mst2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(gct8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mst4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)))
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(mst5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Payment", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel17.setText("Total Amount:");

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel18.setText("Paid:");

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel19.setText(" Balance:");

        mst6.setFont(new java.awt.Font("Times New Roman", 1, 14));
        mst6.setText(" ");
        mst6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mst6.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        mst6.setEnabled(false);
        mst6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mst6KeyPressed(evt);
            }
        });

        mst7.setFont(new java.awt.Font("Times New Roman", 1, 14));
        mst7.setText(" ");
        mst7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mst7.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        mst7.setEnabled(false);
        mst7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mst7KeyPressed(evt);
            }
        });

        mst8.setFont(new java.awt.Font("Times New Roman", 1, 14));
        mst8.setText(" ");
        mst8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mst8.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        mst8.setEnabled(false);
        mst8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mst8KeyPressed(evt);
            }
        });

        mstab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        mstab.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mstabKeyPressed(evt);
            }
        });
        jScrollPane3.setViewportView(mstab);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mst6, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel18)
                        .addGap(18, 18, 18)
                        .addComponent(mst7, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel19)
                        .addGap(18, 18, 18)
                        .addComponent(mst8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(mst6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(mst7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(mst8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                .addContainerGap())
        );

        msclearbtn.setFont(new java.awt.Font("Lucida Sans", 1, 12));
        msclearbtn.setText("Reset");
        msclearbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msclearbtnActionPerformed(evt);
            }
        });
        msclearbtn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                msclearbtnKeyPressed(evt);
            }
        });

        sdatelbl.setFont(new java.awt.Font("Times New Roman", 1, 14));
        sdatelbl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel28.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel28.setText("Purchased Date:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(151, 151, 151)
                                .addComponent(msclearbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sdatelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel28)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sdatelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(msclearbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tabpan.addTab(" Silver_Sale", jPanel2);

        mgclosebtn.setFont(new java.awt.Font("Times New Roman", 1, 14));
        mgclosebtn.setText(" CLOSE");
        mgclosebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mgclosebtnActionPerformed(evt);
            }
        });
        mgclosebtn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mgclosebtnKeyPressed(evt);
            }
        });

        mtxt.setColumns(20);
        mtxt.setFont(new java.awt.Font("Times New Roman", 1, 14));
        mtxt.setRows(5);
        mtxt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jScrollPane1.setViewportView(mtxt);

        jButton1.setFont(new java.awt.Font("Lucida Sans", 1, 12));
        jButton1.setText("Send");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Lucida Sans", 1, 12));
        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel1.setText("Message");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(627, 627, 627)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addComponent(today, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(711, Short.MAX_VALUE)
                .addComponent(mgclosebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(tabpan, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(263, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(today, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(mgclosebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(104, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(tabpan, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void mgt5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mgt5KeyPressed
        // TODO add your handling code here:
        int keycode=evt.getKeyCode();
        if(keycode==10) {
            mgt6.requestFocus(true);

        }
}//GEN-LAST:event_mgt5KeyPressed

    private void mgt3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mgt3KeyPressed
        // TODO add your handling code here:
        int keycode=evt.getKeyCode();
        if(keycode==10) {
            mgt4.requestFocus(true);

        }
}//GEN-LAST:event_mgt3KeyPressed

    private void gct2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gct2KeyPressed
        // TODO add your handling code here:
        int keycode=evt.getKeyCode();
        if(keycode==10) {
            mgt4.requestFocus(true);

        }
}//GEN-LAST:event_gct2KeyPressed

    private void mgt2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mgt2KeyPressed
        // TODO add your handling code here:
        int keycode=evt.getKeyCode();
        if(keycode==10) {
            mgt3.requestFocus(true);

        }
}//GEN-LAST:event_mgt2KeyPressed

    private void mgt4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mgt4KeyPressed
        // TODO add your handling code here:
        int keycode=evt.getKeyCode();
        if(keycode==10) {
            mgt5.requestFocus(true);
        }
}//GEN-LAST:event_mgt4KeyPressed

    private void mgt6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mgt6KeyPressed
        // TODO add your handling code here:
        int keycode=evt.getKeyCode();
        if(keycode==10) {
            mgt7.requestFocus(true);

        }
}//GEN-LAST:event_mgt6KeyPressed

    private void mgt7KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mgt7KeyPressed
        // TODO add your handling code here:
        int keycode=evt.getKeyCode();
        if(keycode==10) {
            mgt8.requestFocus(true);

        }
}//GEN-LAST:event_mgt7KeyPressed

    private void mgt8KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mgt8KeyPressed
        // TODO add your handling code here:
        int keycode=evt.getKeyCode();
        if(keycode==10) {
           // mgt9.requestFocus(true);
        }
}//GEN-LAST:event_mgt8KeyPressed

    private void mgclearbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mgclearbtnActionPerformed
        // TODO add your handling code here:
        gcmb.setSelectedIndex(0);
        mgt2.setText("");
        mgt3.setText("");
        mgt4.setText("");
        mgt5.setText("");
        mgt6.setText("");
        mgt7.setText("");
        mgt8.setText("");
        datelbl.setText("");
        mgtab.setModel(null);
}//GEN-LAST:event_mgclearbtnActionPerformed

    private void mgclearbtnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mgclearbtnKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==java.awt.event.KeyEvent.VK_UP) {
          //  mgclosebtn.requestFocus();
        }
        if(evt.getKeyCode()==java.awt.event.KeyEvent.VK_DOWN) {
           // mgnewbtn.requestFocus();
        }
}//GEN-LAST:event_mgclearbtnKeyPressed

    private void mst5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mst5KeyPressed
        // TODO add your handling code here:
        int keycode=evt.getKeyCode();
        if(keycode==10) {
            mst6.requestFocus(true);

        }
}//GEN-LAST:event_mst5KeyPressed

    private void mst3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mst3KeyPressed
        // TODO add your handling code here:
        int keycode=evt.getKeyCode();
        if(keycode==10) {
            mst4.requestFocus(true);

        }
}//GEN-LAST:event_mst3KeyPressed

    private void gct8KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gct8KeyPressed
        // TODO add your handling code here:
}//GEN-LAST:event_gct8KeyPressed

    private void mst2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mst2KeyPressed
        // TODO add your handling code here
        int keycode=evt.getKeyCode();
        if(keycode==10) {
            mst3.requestFocus(true);

        }
}//GEN-LAST:event_mst2KeyPressed

    private void mst6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mst6KeyPressed
        // TODO add your handling code here:
        int keycode=evt.getKeyCode();
        if(keycode==10) {
            mst7.requestFocus(true);

        }
}//GEN-LAST:event_mst6KeyPressed

    private void mst7KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mst7KeyPressed
        // TODO add your handling code here:
        int keycode=evt.getKeyCode();
        if(keycode==10) {
            mst8.requestFocus(true);

        }
}//GEN-LAST:event_mst7KeyPressed

    private void mst8KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mst8KeyPressed
        
}//GEN-LAST:event_mst8KeyPressed

    private void msclearbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msclearbtnActionPerformed
        // TODO add your handling code here:
        scmb.setSelectedIndex(0);
        mst2.setText("");
        mst3.setText("");
        mst4.setText("");
        mst5.setText("");
        mst6.setText("");
        mst7.setText("");
        mst8.setText("");
        sdatelbl.setText("");
        mstab.setModel(null);

}//GEN-LAST:event_msclearbtnActionPerformed

    private void msclearbtnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_msclearbtnKeyPressed
        
}//GEN-LAST:event_msclearbtnKeyPressed

    private void mgclosebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mgclosebtnActionPerformed
        // TODO add your handling code here:
        Admin.Forms.MainMenu.PanelInfo.removeAll();
        Admin.Forms.MainMenu.PanelInfo.repaint();
}//GEN-LAST:event_mgclosebtnActionPerformed

    private void mgclosebtnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mgclosebtnKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==java.awt.event.KeyEvent.VK_UP) {
          //  mginvoicebtn.requestFocus();
        }
        if(evt.getKeyCode()==java.awt.event.KeyEvent.VK_DOWN) {
            mgclearbtn.requestFocus();
        }
}//GEN-LAST:event_mgclosebtnKeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void gcmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gcmbActionPerformed
    String t1=((String) gcmb.getSelectedItem());
        try {
            Goldcst_model gsm=(Goldcst_model)gs.viewbycid(t1);
            mgt2.setText(gsm.getCname());
            mgt3.setText(gsm.getAddress());
            mgt4.setText(gsm.getCity());
            mgt5.setText(gsm.getPhno());
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, "data not found search another no");
        }
    }//GEN-LAST:event_gcmbActionPerformed

    private void scmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scmbActionPerformed
        // TODO add your handling code here:
        String t1=((String) scmb.getSelectedItem());
        try {
           // Silversale_model ssm=(Silversale_model)gs.viewbycid(t1);
           /* mst2.setText(ssm.getCname());
            mst3.setText(ssm.getAddress());
            mst4.setText(ssm.getCity());
            mst5.setText(ssm.getPhno());
            gettfdata();*/
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, "data not found search another no");
        }
    }//GEN-LAST:event_scmbActionPerformed

    private void mgtabKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mgtabKeyPressed
        // TODO add your handling code here:
        
        
            
        
    }//GEN-LAST:event_mgtabKeyPressed

    private void mstabKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mstabKeyPressed
        // TODO add your handling code here:
        try
        {
            int ro=mstab.getSelectedRow();
            String id=mstab.getModel().getValueAt(ro,0).toString();
        String inam=mstab.getModel().getValueAt(ro,1).toString();
     /*   Silversale_model ssm=(Silversale_model)ss.getAllItmfromTab(id, inam);

            String ta=String.valueOf(ssm.getTotamt());
            mst6.setText(ta);
            String pamt=String.valueOf(ssm.getP_amt());
            mst7.setText(pamt);
            String bal=String.valueOf(ssm.getBal_amt());
            mst8.setText(bal);
            sdatelbl.setText(ssm.getP_date());*/
        }
        catch(Exception e){JOptionPane.showMessageDialog(this,"Dont Select on the blank Row");}

            
    }//GEN-LAST:event_mstabKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(tabpan.getSelectedIndex()==0){t1=(String) gcmb.getSelectedItem();t2=mgt2.getText();}
        if(tabpan.getSelectedIndex()==1){t1=(String)scmb.getSelectedItem();t2=mgt3.getText();}
        t3=mtxt.getText();
        t4=today.getDate().toString();
        boolean v=validatid();
        if(v)
        {
            boolean flag=false;
            flag=gs.messagesave(t1,t2,t3,t4);
            if(flag)
            {
                JOptionPane.showMessageDialog(this,"message sent success fully and saved as draft");
            }
            else
            {
                JOptionPane.showMessageDialog(this,"sorry message not saved for in draft");
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void trsidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trsidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_trsidActionPerformed
    private boolean validatid()
    {
        if(t1.matches("-Select-")){JOptionPane.showMessageDialog(this,"please select the Customer id no for confermation");return false;}
        if(t3.length()==0){JOptionPane.showMessageDialog(this, "blank message cant be sent please enter the message");return false;}
        if(t4.length()==0){JOptionPane.showMessageDialog(this, "please select the date");return false;}
        return true;
    }
    public void gettfdata()
    {
         String t1=((String) scmb.getSelectedItem());
        try {
      /*  Silversale_model ssm=(Silversale_model)ss.viewbyc_id(t1);
            
            String ta=String.valueOf(ssm.getTotamt());
            mst6.setText(ta);
            String pamt=String.valueOf(ssm.getP_amt());
            mst7.setText(pamt);
            String bal=String.valueOf(ssm.getBal_amt());
            mst8.setText(bal);
            sdatelbl.setText(ssm.getP_date());
            generateSilverViews(t1);*/
            } catch(Exception e) {
            JOptionPane.showMessageDialog(null, "data not found search another no");}
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel datelbl;
    private javax.swing.JComboBox gcmb;
    private javax.swing.JScrollPane gct2;
    private javax.swing.JScrollPane gct8;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton mgclearbtn;
    private javax.swing.JButton mgclosebtn;
    private javax.swing.JTextField mgt2;
    private javax.swing.JTextArea mgt3;
    private javax.swing.JTextField mgt4;
    private javax.swing.JTextField mgt5;
    private javax.swing.JTextField mgt6;
    private javax.swing.JTextField mgt7;
    private javax.swing.JTextField mgt8;
    private javax.swing.JTable mgtab;
    private javax.swing.JButton msclearbtn;
    private javax.swing.JTextField mst2;
    private javax.swing.JTextArea mst3;
    private javax.swing.JTextField mst4;
    private javax.swing.JTextField mst5;
    private javax.swing.JTextField mst6;
    private javax.swing.JTextField mst7;
    private javax.swing.JTextField mst8;
    private javax.swing.JTable mstab;
    private javax.swing.JTextArea mtxt;
    private javax.swing.JComboBox scmb;
    private javax.swing.JLabel sdatelbl;
    private javax.swing.JTabbedPane tabpan;
    private com.toedter.calendar.JDateChooser today;
    private javax.swing.JComboBox trsid;
    // End of variables declaration//GEN-END:variables
    
    private boolean Validatefields() {
        throw new UnsupportedOperationException("Not yet implemented");
    }
    
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        int width = getWidth();
        int height = getHeight();
        int shadowGap = this.shadowGap;
        Color shadowColorA = new Color(shadowColor.getRed(),
	shadowColor.getGreen(), shadowColor.getBlue(), shadowAlpha);
        Graphics2D graphics = (Graphics2D) g;

        //Sets antialiasing if HQ.
        if (highQuality) {
            graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING,
			RenderingHints.VALUE_ANTIALIAS_ON);
        }

        //Draws shadow borders if any.
        if (shady) {
            graphics.setColor(shadowColorA);
            graphics.fillRoundRect(
                    shadowOffset,// X position
                    shadowOffset,// Y position
                    width - strokeSize - shadowOffset, // width
                    height - strokeSize - shadowOffset, // height
                    arcs.width, arcs.height);// arc Dimension
        } else {
            shadowGap = 1;
        }

        //Draws the rounded opaque panel with borders.
        graphics.setColor(getBackground());
        graphics.fillRoundRect(0, 0, width - shadowGap, height - shadowGap, arcs.width, arcs.height);
        graphics.setColor(getForeground());
        graphics.setStroke(new BasicStroke(strokeSize));
        graphics.drawRoundRect(0, 0, width - shadowGap,
		height - shadowGap, arcs.width, arcs.height);

        //Sets strokes to default, is better.
        graphics.setStroke(new BasicStroke());
    }
    //fun for creating shadow Stops**************************************************************
}
