/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Purchase;
//For shadow
//import Sales.*;
import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics2D;
import java.awt.RenderingHints;

import javax.swing.*;
import java.awt.Graphics;

/**
 *
 * @author Vicky
 */
public class PurchaseToolBar extends javax.swing.JPanel {

     //attrib for shadow starts************************************************
    protected int strokeSize = 1;
    protected Color shadowColor = Color.black;
    protected boolean shady = true;
    protected boolean highQuality = true;
    protected Dimension arcs = new Dimension(20, 20);
    protected int shadowGap = 5;
    protected int shadowOffset = 4;
    protected int shadowAlpha = 150;
//attrib for shadow stops************************************************


    /**
     * Creates new form SalesPanel
     */
    public PurchaseToolBar()
    {
     
      //  private BufferedImage img;
        setOpaque(false);
        initComponents();

        System.out.println("Done.........");
       
        //ImageIcon a=new ImageIcon("C:\\Users\\Vicky\\Documents\\NetBeansProjects\\SampleCollegeDemo\\src\\images\\logo_1129757_web.jpg");
      //  jButton16.setText("<Html><Center>"+"Curricular"+"<br>"+"Activities"+"</center></html>");
       // jButton16.setIcon(a);
    }
    
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton15 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        Purchase_Excel = new javax.swing.JButton();
        Gold_Purchase = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        Purchase_Search = new javax.swing.JButton();
        Purchase_Detailview = new javax.swing.JButton();

        jButton15.setText("jButton15");

        setBackground(java.awt.SystemColor.controlHighlight);
        setMaximumSize(new java.awt.Dimension(1000, 90));
        setMinimumSize(new java.awt.Dimension(1000, 90));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1300, 125));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Gold/Silver Sale", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(770, 100));

        Purchase_Excel.setFont(new java.awt.Font("Lucida Sans", 1, 12));
        Purchase_Excel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logos/student/excel.png"))); // NOI18N
        Purchase_Excel.setText("  From Excel");
        Purchase_Excel.setIconTextGap(0);
        Purchase_Excel.setMaximumSize(new java.awt.Dimension(35, 10));
        Purchase_Excel.setMinimumSize(new java.awt.Dimension(35, 10));
        Purchase_Excel.setPreferredSize(new java.awt.Dimension(35, 10));
        Purchase_Excel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Purchase_ExcelActionPerformed(evt);
            }
        });

        Gold_Purchase.setFont(new java.awt.Font("Times New Roman", 1, 18));
        Gold_Purchase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logos/Staff/gold_purch.png"))); // NOI18N
        Gold_Purchase.setText(" Gold_Purchase");
        Gold_Purchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Gold_PurchaseActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logos/Staff/silver_purch.png"))); // NOI18N
        jButton2.setText("Silver_Purchase");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Gold_Purchase)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addGap(26, 26, 26)
                .addComponent(Purchase_Excel, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Gold_Purchase, javax.swing.GroupLayout.PREFERRED_SIZE, 66, Short.MAX_VALUE)
                    .addComponent(Purchase_Excel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Search/View", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N
        jPanel2.setOpaque(false);

        Purchase_Search.setFont(new java.awt.Font("Lucida Sans", 1, 12));
        Purchase_Search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logos/student/search.png"))); // NOI18N
        Purchase_Search.setText("Search");
        Purchase_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Purchase_SearchActionPerformed(evt);
            }
        });

        Purchase_Detailview.setFont(new java.awt.Font("Lucida Sans", 1, 12));
        Purchase_Detailview.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logos/student/Detail.png"))); // NOI18N
        Purchase_Detailview.setText("Detail View");
        Purchase_Detailview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Purchase_DetailviewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Purchase_Search)
                .addGap(18, 18, 18)
                .addComponent(Purchase_Detailview, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Purchase_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Purchase_Detailview, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 683, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(229, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Purchase_ExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Purchase_ExcelActionPerformed

        
        
        Admin.Forms.MainMenu.PanelInfo.removeAll();
         Admin.Forms.MainMenu.PanelInfo.repaint();
          /* JPanel p2helper = new Excel();
             setMainPanel(p2helper);*/
    }//GEN-LAST:event_Purchase_ExcelActionPerformed

    private void Purchase_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Purchase_SearchActionPerformed
        // TODO add your handling code here:
         Admin.Forms.MainMenu.PanelInfo.removeAll();
         Admin.Forms.MainMenu.PanelInfo.repaint();
          // JPanel p2helper = new Purchase_Search();
            // setMainPanel(p2helper);
    }//GEN-LAST:event_Purchase_SearchActionPerformed

    private void Purchase_DetailviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Purchase_DetailviewActionPerformed
        // TODO add your handling code here:
         Admin.Forms.MainMenu.PanelInfo.removeAll();
         Admin.Forms.MainMenu.PanelInfo.repaint();
          // Purchase_Detailview p2helper = new Purchase_Detailview();
            // setMainPanel(p2helper);
    }//GEN-LAST:event_Purchase_DetailviewActionPerformed

    private void Gold_PurchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Gold_PurchaseActionPerformed
        // TODO add your handling code here:
        Admin.Forms.MainMenu.PanelInfo.removeAll();
         Admin.Forms.MainMenu.PanelInfo.repaint();
           JPanel p2helper = new Pur_Gold();
             setMainPanel(p2helper);
    }//GEN-LAST:event_Gold_PurchaseActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         Admin.Forms.MainMenu.PanelInfo.removeAll();
         Admin.Forms.MainMenu.PanelInfo.repaint();
           JPanel p2helper = new Pur_Silver();
             setMainPanel(p2helper);

    }//GEN-LAST:event_jButton2ActionPerformed

     public void setMainPanel(JPanel subPanel) {
    JPanel PanelInfo=  Admin.Forms.MainMenu.PanelInfo;
    PanelInfo.removeAll();
     PanelInfo.add(subPanel);
     PanelInfo.validate();
     PanelInfo.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Gold_Purchase;
    private javax.swing.JButton Purchase_Detailview;
    private javax.swing.JButton Purchase_Excel;
    private javax.swing.JButton Purchase_Search;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

 //fun for creating shadow Starts**************************************************************
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        int width = getWidth();
        int height = getHeight();
        int shadowGap = this.shadowGap;
        Color shadowColorA = new Color(shadowColor.getRed(),
	shadowColor.getGreen(), shadowColor.getBlue(), shadowAlpha);
        Graphics2D graphics = (Graphics2D) g;

        //Sets antialiasing if HQ.
        if (highQuality) {
            graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING,
			RenderingHints.VALUE_ANTIALIAS_ON);
        }

        //Draws shadow borders if any.
        if (shady) {
            graphics.setColor(shadowColorA);
            graphics.fillRoundRect(
                    shadowOffset,// X position
                    shadowOffset,// Y position
                    width - strokeSize - shadowOffset, // width
                    height - strokeSize - shadowOffset, // height
                    arcs.width, arcs.height);// arc Dimension
        } else {
            shadowGap = 1;
        }

        //Draws the rounded opaque panel with borders.
        graphics.setColor(getBackground());
        graphics.fillRoundRect(0, 0, width - shadowGap, height - shadowGap, arcs.width, arcs.height);
        graphics.setColor(getForeground());
        graphics.setStroke(new BasicStroke(strokeSize));
        graphics.drawRoundRect(0, 0, width - shadowGap,
		height - shadowGap, arcs.width, arcs.height);

        //Sets strokes to default, is better.
        graphics.setStroke(new BasicStroke());
    }

    private void setMainPanel(Purchase_Detailview p2helper) {
        throw new UnsupportedOperationException("Not yet implemented");
    }
    //fun for creating shadow Stops*************************************************************
}
